### ISSUE TITLE
InterruptedException when hole filling is disabled 

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1010]
`Caused by: java.lang.RuntimeException: java.lang.InterruptedException: sleep interrupted
                at org.corfudb.runtime.view.replication.NeverHoleFillPolicy.peekUntilHoleFillRequired(NeverHoleFillPolicy.java:47)
                at org.corfudb.runtime.view.replication.AbstractReplicationProtocol.read(AbstractReplicationProtocol.java:41)
                at org.corfudb.runtime.view.AddressSpaceView.lambda$fetch$25(AddressSpaceView.java:345)
                at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:76)
                at org.corfudb.runtime.view.AddressSpaceView.fetch(AddressSpaceView.java:343)
                at org.corfudb.runtime.view.AddressSpaceView.cacheFetch(AddressSpaceView.java:289)
                at org.corfudb.runtime.view.AddressSpaceView.access$000(AddressSpaceView.java:43)
                at org.corfudb.runtime.view.AddressSpaceView$1.load(AddressSpaceView.java:56)
                at org.corfudb.runtime.view.AddressSpaceView$1.load(AddressSpaceView.java:53)
                at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3070)
                at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:144)
                at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:1895)
                at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
                at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1893)
                at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1876)
                at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
                at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
                at org.corfudb.runtime.view.AddressSpaceView.read(AddressSpaceView.java:152)
                at org.corfudb.runtime.view.stream.BackpointerStreamView.read(BackpointerStreamView.java:154)
                at org.corfudb.runtime.view.stream.BackpointerStreamView.followBackpointers(BackpointerStreamView.java:243)
                at org.corfudb.runtime.view.stream.BackpointerStreamView.fillReadQueue(BackpointerStreamView.java:435)`

**Comment by no2chem** [comment]
@Maithem Is this problem still occurring? When does it occur?

**Comment by Maithem** [comment]
No longer observed.
