### ISSUE TITLE
Orchestrator Service is causing builds to fail

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1073]
## Overview

**Bug report.** The orchestrator service (#1014) is causing builds to fail consistently on master in unrelated tests. I have also observed tests hanging tests locally. Unless the orchestrator service can be quickly patched, we'll have to revert #1014.

**Comment by no2chem** [comment]
See the build logs on Travis for master:

https://travis-ci.org/CorfuDB/CorfuDB/branches

It doesn't seem consistent, but usually somewhere inside SMRMapTest. On my local machine addNodeIT consistently fails due to a file error.

**Comment by Maithem** [comment]
What is the error that you see on your local machine, is it this:

java.nio.file.NoSuchFileException: /tmp/1513210693888-0/localhost_9001_consolelog
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3292)
	at org.corfudb.integration.AbstractIT$StreamGobbler.lambda$run$0(AbstractIT.java:228)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.corfudb.integration.AbstractIT$StreamGobbler.run(AbstractIT.java:226)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.nio.file.NoSuchFileException: /tmp/1513210693888-0/localhost_9000_consolelog
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3292)
	at org.corfudb.integration.AbstractIT$StreamGobbler.lambda$run$0(AbstractIT.java:228)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.corfudb.integration.AbstractIT$StreamGobbler.run(AbstractIT.java:226)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by no2chem** [comment]
Yeah, that seems to be it. Different than Travis, though


On Wed, Dec 13, 2017 at 4:20pm, Maithem < notifications@github.com [notifications@github.com] > wrote:
What is the error that you see on your local machine, is it this:

java.nio.file.NoSuchFileException: /tmp/1513210693888-0/localhost_9001_consolelog
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
at java.nio.file.Files.newOutputStream(Files.java:216)
at java.nio.file.Files.write(Files.java:3292)
at org.corfudb.integration.AbstractIT$StreamGobbler.lambda$run$0(AbstractIT.java:228)
at java.util.Iterator.forEachRemaining(Iterator.java:116)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
at org.corfudb.integration.AbstractIT$StreamGobbler.run(AbstractIT.java:226)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
java.nio.file.NoSuchFileException: /tmp/1513210693888-0/localhost_9000_consolelog
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
at java.nio.file.Files.newOutputStream(Files.java:216)
at java.nio.file.Files.write(Files.java:3292)
at org.corfudb.integration.AbstractIT$StreamGobbler.lambda$run$0(AbstractIT.java:228)
at java.util.Iterator.forEachRemaining(Iterator.java:116)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
at org.corfudb.integration.AbstractIT$StreamGobbler.run(AbstractIT.java:226)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by Maithem** [comment]
I looked at many failures after my two PRs went in and it most fails on unit tests that are not related to the Orchestrator, a lot of unit tests that I've seen fail before intermittently. It might be the case that #940 degraded performance such that the timings are off in the unit tests, thus the apparent higher frequency in failures.

**Comment by no2chem** [comment]
Well we need to get tests working again. I observe that the last two PRs are causing failures, consistently. We can revert #940 first, if you think that is causing the problem.

**Comment by Maithem** [comment]
I triggering the CI for two branches, one with the orchestrator and the other with 940, let's wait and see if they fail at the same frequency.

**Comment by no2chem** [comment]
Ok. Focus on fixing CI, I'll take care of rpc timeout and review your PR.


On Wed, Dec 13, 2017 at 6:16pm, Maithem < notifications@github.com [notifications@github.com] > wrote:
I triggering the CI for two branches, one with the orchestrator and the other with 940, let's wait and see if they fail at the same frequency.

**Comment by zalokhan** [comment]
Fixed.
