### ISSUE TITLE
testSequencerFailover test occasionally fails

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1080]
## Overview

**Bug report.**  The testSequencerFailover test randomly fails due to a failed epoch change.

```
testSequencerFailover                                       [FAIL - ComparisonFailure:L429]

sealDoesNotModifyClientRouterEpoch                          [PASS]

testNodeHealing                                             [PASS]

sequencerFailoverBackpointerCheck                           [PASS]

updateTrailingLayoutServers                                 [PASS]

removeSingleNodeFailure                                     [PASS]

Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 83.43 sec <<< FAILURE! - in org.corfudb.runtime.view.ManagementViewTest

testSequencerFailover(org.corfudb.runtime.view.ManagementViewTest)  Time elapsed: 6.055 sec  <<< FAILURE!

org.junit.ComparisonFailure: expected:<...nresponsiveServers=[[test:0], epoch=2])> but was:<...nresponsiveServers=[[], epoch=3])>

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

	at org.corfudb.runtime.view.ManagementViewTest.testSequencerFailover(ManagementViewTest.java:429)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

	at org.corfudb.AbstractCorfuTest$1$1.evaluate(AbstractCorfuTest.java:76)

	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)

	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)

	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)

	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)

	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)

	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Comment by zalokhan** [comment]
This should be fixed by the new failure detector #1162
