### ISSUE TITLE
AddNodeTest occasionally fails

### ISSUE THREAD

**Issue by no2chem** [CorfuDB/CorfuDB#1085]
## Overview

**Bug report.** The AddNodeTest sometimes fails after long timeouts with the following failure:

```
AddNodeTest                                                 [FAIL - ComparisonFailure:L84]
java.nio.file.NoSuchFileException: /var/folders/yq/8xzjxn_x5fz6yy7blrl1jn840000gn/T/1513256646935-0/localhost_9001_consolelog
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at java.nio.file.Files.write(Files.java:3292)
        at org.corfudb.integration.AbstractIT$StreamGobbler.lambda$run$0(AbstractIT.java:228)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.corfudb.integration.AbstractIT$StreamGobbler.run(AbstractIT.java:226)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 33.363 sec <<< FAILURE! - in org.corfudb.integration.AddNodeIT
AddNodeTest(org.corfudb.integration.AddNodeIT)  Time elapsed: 32.534 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[2]> but was:<[1]>
        at org.corfudb.integration.AddNodeIT.AddNodeTest(AddNodeIT.java:84)
```

**Comment by no2chem** [comment]
Occasionally, it also gets deadlocked on a WrongEpochException as well:

```
15:01:13.146 WARN  [ForkJoinPool.commonPool-worker-2] o.c.r.CorfuRuntime - Tried to get layout from localhost:9001 but failed with exception:
 java.util.concurrent.ExecutionException: org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.corfudb.runtime.CorfuRuntime.lambda$fetchLayout$4(CorfuRuntime.java:523)
Caused by: org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]
	at org.corfudb.runtime.clients.BaseClient.handleWrongEpoch(BaseClient.java:165)
	at org.corfudb.runtime.clients.ClientMsgHandler.handle(ClientMsgHandler.java:76)
	at org.corfudb.runtime.clients.IClient.handleMessage(IClient.java:40)
15:01:13.146 WARN  [main] o.c.r.v.AbstractView - Got a wrong epoch exception, updating epoch to 0 and invalidate view
 15:01:13.146 WARN  [main] o.c.r.v.AbstractView - Got a wrong epoch exception, updating epoch to 0 and invalidate view
 15:01:13.147 WARN  [ForkJoinPool.commonPool-worker-2] o.c.r.CorfuRuntime - Tried to get layout from localhost:9001 but failed with exception:
 java.util.concurrent.ExecutionException: org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.corfudb.runtime.CorfuRuntime.lambda$fetchLayout$4(CorfuRuntime.java:523)
Caused by: org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]
	at org.corfudb.runtime.clients.BaseClient.handleWrongEpoch(BaseClient.java:165)
	at org.corfudb.runtime.clients.ClientMsgHandler.handle(ClientMsgHandler.java:76)
	at org.corfudb.runtime.clients.IClient.handleMessage(IClient.java:40)
15:01:13.147 WARN  [main] o.c.r.v.AbstractView - Got a wrong epoch exception, updating epoch to 0 and invalidate view
 15:01:13.147 WARN  [main] o.c.r.v.AbstractView - Got a wrong epoch exception, updating epoch to 0 and invalidate view
 15:01:13.147 WARN  [ForkJoinPool.commonPool-worker-2] o.c.r.CorfuRuntime - Tried to get layout from localhost:9001 but failed with exception:
 java.util.concurrent.ExecutionException: org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.corfudb.runtime.CorfuRuntime.lambda$fetchLayout$4(CorfuRuntime.java:523)
Caused by: org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]
	at org.corfudb.runtime.clients.BaseClient.handleWrongEpoch(BaseClient.java:165)
	at org.corfudb.runtime.clients.ClientMsgHandler.handle(ClientMsgHandler.java:76)
	at org.corfudb.runtime.clients.IClient.handleMessage(IClient.java:40)
15:01:13.148 WARN  [main] o.c.r.v.AbstractView - Got a wrong epoch exception, updating epoch to 0 and invalidate view
 15:01:13.148 WARN  [ForkJoinPool.commonPool-worker-2] o.c.r.CorfuRuntime - Tried to get layout from localhost:9001 but failed with exception:
 java.util.concurrent.ExecutionException: org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.corfudb.runtime.CorfuRuntime.lambda$fetchLayout$4(CorfuRuntime.java:523)
Caused by: org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]
	at org.corfudb.runtime.clients.BaseClient.handleWrongEpoch(BaseClient.java:165)
	at org.corfudb.runtime.clients.ClientMsgHandler.handle(ClientMsgHandler.java:76)
	at org.corfudb.runtime.clients.IClient.handleMessage(IClient.java:40)
```
