### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by medhavidhawan** [CorfuDB/CorfuDB#114]
ByteBuff.release is coded wrong

I am getting the following error when I run any test

ERROR org.corfudb.runtime.clients.NettyClientRouter - Exception during channel handling.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:50) ~[nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at org.corfudb.protocols.wireprotocol.CorfuMsg.release(CorfuMsg.java:174) ~[nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at org.corfudb.runtime.clients.NettyClientRouter.channelRead0(NettyClientRouter.java:380) ~[nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at org.corfudb.runtime.clients.NettyClientRouter.channelRead0(NettyClientRouter.java:35) ~[nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) [nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) [nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263) [nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) [nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:298) [nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [nsx-datastore-eval-1.0-SNAPSHOT-shaded.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_7]

I looked up Netty code and it seems like we are trying to release Netty's reference counted buffer which does the release automatically.

**Comment by no2chem** [comment]
the underlying bug is actually the client ID being checked with equality instead of .equals() since it got changed to an UUID. The buffer release is also an issue which is addressed in #115
