### ISSUE TITLE
Management Client Epoll Bug

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1221]
## Overview
**Bug report.** 

Starting the server with -i epoll breaks the management client. 

` 2018-03-14 16:12:44,059 WARN  [ForkJoinPool.commonPool-worker-1] o.c.r.CorfuRuntime - Tried to get layout from localhost:9000 but failed with exception:
 java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
2018-03-14 16:12:44,059 WARN  [ForkJoinPool.commonPool-worker-1] o.c.r.CorfuRuntime - Couldn't connect to any up-to-date layout servers, retrying in PT1S
 2018-03-14 16:12:45,054 INFO  [client-5] o.c.r.c.NettyClientRouter - connectAsync[tcp://localhost:9000/]: Channel connection failed, reconnecting...
 2018-03-14 16:12:45,560 WARN  [ForkJoinPool.commonPool-worker-1] o.c.r.CorfuRuntime - Tried to get layout from localhost:9000 but failed with exception:
 java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
2018-03-14 16:12:45,560 WARN  [ForkJoinPool.commonPool-worker-1] o.c.r.CorfuRuntime - Couldn't connect to any up-to-date layout servers, retrying in PT1S
 2018-03-14 16:12:45,714 ERROR [worker-0] o.c.i.NettyServerRouter - Error in handling inbound message, {}
 io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
`

**Comment by Maithem** [comment]
outdated.

**Comment by Maithem** [comment]
outdated.
