### ISSUE TITLE
Error during serialization

### ISSUE THREAD

**Issue by redbrick9** [CorfuDB/CorfuDB#1312]
I built up a corfu server based on TOT run into the following exception.

15:42:08.214 [netty-2] ERROR org.corfudb.protocols.wireprotocol.NettyCorfuMessageEncoder - encode: Error during serialization!
java.lang.IndexOutOfBoundsException: readerIndex: 2952 (expected: 0 <= readerIndex <= writerIndex(1476))
	at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:103) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1073) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1062) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at org.corfudb.protocols.wireprotocol.LogData.doSerialize(LogData.java:203) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.ICorfuPayload.serialize(ICorfuPayload.java:278) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.WriteRequest.doSerialize(WriteRequest.java:50) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.ICorfuPayload.serialize(ICorfuPayload.java:278) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.CorfuPayloadMsg.serialize(CorfuPayloadMsg.java:46) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.NettyCorfuMessageEncoder.encode(NettyCorfuMessageEncoder.java:26) [runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.NettyCorfuMessageEncoder.encode(NettyCorfuMessageEncoder.java:15) [runtime-0.2.0-SNAPSHOT.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by Maithem** [comment]
Hi @redbrick9, can you provide the client code that is doing the write? It might be the case that your are writing with the default serializer, but the default serializer can't serialize your object, so you might need to register a non-default serializer.

**Comment by redbrick9** [comment]
Thanks @Maithem for the reply. The client directly write byte array into the corfu. The writes look be good, since I can get them with the key. So I think the error is irrelevant to the writes.

Weird thing is the error disappeared when I changed logging configuration from logback to log4j.

Let me close the bug for now, if I run into the similar symptom, I will create new one with more detailed information.

**Comment by redbrick9** [comment]
public class CorfuClient implements StoreClient {
    private Logger logger = LoggerFactory.getLogger(CorfuClient.class);

    private final String endpoint;
    private CorfuRuntime runtime;
    private String state;
    private CorfuTable table;
    private String streamName = "book";

    public CorfuClient(String endpoint) {
        this.endpoint = endpoint;
        this.state = "DISCONNECTED";
    }

    public CorfuRuntime getRuntime() {
        return runtime;
    }

    public CorfuTable<UUID, byte[]> getTable() {
        return table;
    }

    public void connect() {
        connect(endpoint);
        state = "CONNECTED";
        table = getCorfuTable();
    }

    private void connect(String endpoint) {
        CorfuRuntimeParameters corfuRuntimeParameters = CorfuRuntimeParameters
            .builder()
            .build();
        NodeLocator nodeLocator = NodeLocator.parseString(endpoint);
        List<NodeLocator> layoutServers = new ArrayList<NodeLocator>();
        layoutServers.add(nodeLocator);
        corfuRuntimeParameters.setLayoutServers(layoutServers);
        runtime = CorfuRuntime.fromParameters(corfuRuntimeParameters).connect();
        Set<UUID> streamIds = new HashSet<>();
        streamIds.add(runtime.getStreamID(streamName));
    }

    private CorfuTable<UUID, byte[]> getCorfuTable() {
        return runtime.getObjectsView()
            .build()
            .setType(CorfuTable.class)
            .setStreamName(streamName)
            .setTypeToken(new TypeToken<CorfuTable<UUID, byte[]>>() {})
            .setSerializer(Serializers.JAVA)
            .open();
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("CorfuClient{");
        sb.append("endpoint='").append(endpoint).append('\'');
        sb.append(", runtime=").append(runtime);
        sb.append(", state='").append(state).append('\'');
        sb.append(", table=").append(table);
        sb.append(", streamName='").append(streamName).append('\'');
        sb.append('}');
        return sb.toString();
    }

    @Override
    public void write(int clientNum, int size) {
        connect();
        for (int i = 0; i < clientNum; i++) {
            UUID uuid = UUID.randomUUID();
            byte[] bytes = new byte[size];
            logger.debug("Write update data: byte array, size: {}", bytes.length);
            table.put(uuid, bytes);
        }
    }
}

**Comment by redbrick9** [comment]
Error log.

2018-06-06 10:13:41.270 UTC DEBUG [main] [o.c.r.v.r.QuorumReplicationProtocol] Write at {} 181
2018-06-06 10:13:41.271 UTC ERROR [netty-3] [o.c.p.w.NettyCorfuMessageEncoder] encode: Error during serialization!
java.lang.IndexOutOfBoundsException: readerIndex: 2438 (expected: 0 <= readerIndex <= writerIndex(1219))
	at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:103) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1073) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1062) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at org.corfudb.protocols.wireprotocol.LogData.doSerialize(LogData.java:203) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.ICorfuPayload.serialize(ICorfuPayload.java:278) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.WriteRequest.doSerialize(WriteRequest.java:50) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.ICorfuPayload.serialize(ICorfuPayload.java:278) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.CorfuPayloadMsg.serialize(CorfuPayloadMsg.java:46) ~[runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.NettyCorfuMessageEncoder.encode(NettyCorfuMessageEncoder.java:26) [runtime-0.2.0-SNAPSHOT.jar:?]
	at org.corfudb.protocols.wireprotocol.NettyCorfuMessageEncoder.encode(NettyCorfuMessageEncoder.java:15) [runtime-0.2.0-SNAPSHOT.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
2018-06-06 10:13:41.271 UTC ERROR [netty-3] [o.c.p.w.NettyCorfuMessageEncoder] encode: CorfuMsg(clientID=877a1b30-8f7c-4666-a51a-4acd480003d1, requestID=80, epoch=0, buf=null, msgType=WRITE), buffer size: 2048
2018-06-06 10:13:41.278 UTC DEBUG [main] [o.c.r.o.VersionLockedObject] Sync[CorfuTable[38f7]@181] Upcall Result 181

**Comment by redbrick9** [comment]
my local layout

{
  "layoutServers": [
    "localhost:9000",
    "localhost:9001",
    "localhost:9002"
  ],  
  "sequencers": [
    "localhost:9000"
  ],  
  "segments": [
    {   
      "replicationMode": "QUORUM_REPLICATION",
      "start": 0,
      "end": -1, 
      "stripes": [
        {
          "logServers": [
            "localhost:9000",
            "localhost:9001",
            "localhost:9002"
          ]
        }
      ]   
    }   
  ],  
  "epoch": 0
}

**Comment by redbrick9** [comment]
Changed replication mode to CHAIN_REPLICATION, I didn't observe this problem.

**Comment by redbrick9** [comment]
Hi guys,

Can someone help confirm if this is a real bug for Quorum replication? Or I made a wrong configuration.

Thanks,
redbrick9

**Comment by Maithem** [comment]
Hey @redbrick9 , Quorum replication is currently not supported. We only support chain replication for cluster mode.

**Comment by redbrick9** [comment]
Got it, thank you very much.
