### ISSUE TITLE
Fault Detectors Stop Running

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1374]
**Bug report.**

In a system of two nodes, reboot both nodes at the same time causes a live lock, which blocks the fault detectors from detecting and correcting the system epochs.

**server log**
 2018-07-13 19:06:43,065 WARN  [initialization task thread] o.c.r.v.AbstractView - Timeout executing remote call, invalidating view and retrying in PT1Ss
 2018-07-13 19:06:44,066 TRACE [initialization task thread] o.c.r.c.NettyClientRouter - Sent message: CorfuMsg(clientID=34038278-1b2d-48d6-970e-92a102aba9ef, requestID=926, epoch=2, buf=null, msgType=TRIM_MARK_REQUEST)

**client log**

 19:06:54.737 INFO  [netty-5] o.c.r.c.NettyClientRouter - connectAsync[tcp://localhost:9002/]: Channel connection failed, reconnecting...
 19:06:54.739 WARN  [Thread-2] o.c.r.v.AbstractView - Server still not ready. Waiting for server to start accepting requests.
 19:06:55.239 WARN  [Thread-1] o.c.r.v.AbstractView - Timeout executing remote call, invalidating view and retrying in PT1Ss
 19:06:55.738 INFO  [netty-5] o.c.r.c.NettyClientRouter - connectAsync[tcp://localhost:9002/]: Channel connection failed, reconnecting...
 19:06:55.738 INFO  [netty-6] o.c.r.c.NettyClientRouter - connectAsync[tcp://localhost:9002/]: Channel connection failed, reconnecting...
 19:06:55.738 INFO  [netty-5] o.c.r.c.NettyClientRouter - connectAsync[tcp://localhost:9002/]: Channel connection failed, reconnecting...
 19:06:55.739 WARN  [ForkJoinPool.commonPool-worker-1] o.c.r.CorfuRuntime - Tried to get layout from localhost:9002 but failed with exception:
 java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.corfudb.runtime.CorfuRuntime.lambda$fetchLayout$6(CorfuRuntime.java:716)
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.corfudb.runtime.clients.NettyClientRouter.sendMessageAndGetCompletable(NettyClientRouter.java:410)
19:06:55.740 WARN  [Thread-2] o.c.r.v.AbstractView - Server still not ready. Waiting for server to start accepting requests.

**Comment by Maithem** [comment]
This seems to happen because some tasks run on a single thread, but never finish executing. We should allow the cancellation of tasks that the management agent runs.
