### ISSUE TITLE
System crash after adding ~7M entries

### ISSUE THREAD

**Issue by ohadshacham** [CorfuDB/CorfuDB#141]
Hi,

After adding ~7M entries, the client crashes with the following exception.
Could you please help?

Thx,
Ohad

java.lang.NullPointerException
	at org.corfudb.runtime.view.Layout.getLogUnitClient(Layout.java:218)
	at org.corfudb.runtime.view.ChainReplicationView.write(ChainReplicationView.java:71)
	at org.corfudb.runtime.view.AddressSpaceView.lambda$write$28(AddressSpaceView.java:142)
	at org.corfudb.runtime.view.AddressSpaceView$$Lambda$190/1388907830.apply(Unknown Source)
	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:74)
	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:140)
	at org.corfudb.runtime.view.StreamsView.acquireAndWrite(StreamsView.java:115)
	at org.corfudb.runtime.view.StreamsView.write(StreamsView.java:81)
	at com.yahoo.ycsb.db.CorfuClient.insert(CorfuClient.java:181)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:208)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:793)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:620)
	at com.yahoo.ycsb.ClientThread.run(Client.java:329)
java.lang.NullPointerExceptionjava.lang.NullPointerException

	at org.corfudb.runtime.view.Layout.getLogUnitClient(Layout.java:218)
	at org.corfudb.runtime.view.Layout.getLogUnitClient(Layout.java:218)	at org.corfudb.runtime.view.ChainReplicationView.write(ChainReplicationView.java:71)

	at org.corfudb.runtime.view.ChainReplicationView.write(ChainReplicationView.java:71)
	at org.corfudb.runtime.view.AddressSpaceView.lambda$write$28(AddressSpaceView.java:142)	at org.corfudb.runtime.view.AddressSpaceView.lambda$write$28(AddressSpaceView.java:142)

	at org.corfudb.runtime.view.AddressSpaceView$$Lambda$190/1388907830.apply(Unknown Source)	at org.corfudb.runtime.view.AddressSpaceView$$Lambda$190/1388907830.apply(Unknown Source)

	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:74)
	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:74)	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:140)

	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:140)	at org.corfudb.runtime.view.StreamsView.acquireAndWrite(StreamsView.java:115)

	at org.corfudb.runtime.view.StreamsView.write(StreamsView.java:81)	at org.corfudb.runtime.view.StreamsView.acquireAndWrite(StreamsView.java:115)

	at com.yahoo.ycsb.db.CorfuClient.insert(CorfuClient.java:181)	at org.corfudb.runtime.view.StreamsView.write(StreamsView.java:81)

	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:208)	at com.yahoo.ycsb.db.CorfuClient.insert(CorfuClient.java:181)

	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:793)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:208)	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:620)

	at com.yahoo.ycsb.ClientThread.run(Client.java:329)	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:793)

	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:620)
	at com.yahoo.ycsb.ClientThread.run(Client.java:329)
java.lang.NullPointerException
	at org.corfudb.runtime.view.Layout.getLogUnitClient(Layout.java:218)
	at org.corfudb.runtime.view.ChainReplicationView.write(ChainReplicationView.java:71)
	at org.corfudb.runtime.view.AddressSpaceView.lambda$write$28(AddressSpaceView.java:142)
	at org.corfudb.runtime.view.AddressSpaceView$$Lambda$190/1388907830.apply(Unknown Source)
	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:74)
	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:140)
	at org.corfudb.runtime.view.StreamsView.acquireAndWrite(StreamsView.java:115)
	at org.corfudb.runtime.view.StreamsView.write(StreamsView.java:81)
	at com.yahoo.ycsb.db.CorfuClient.insert(CorfuClient.java:181)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:208)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:793)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:620)
	at com.yahoo.ycsb.ClientThread.run(Client.java:329)
java.lang.NullPointerException
	at org.corfudb.runtime.view.Layout.getSequencer(Layout.java:120)
	at org.corfudb.runtime.view.SequencerView.lambda$nextToken$24(SequencerView.java:27)
	at org.corfudb.runtime.view.SequencerView$$Lambda$155/2004931730.apply(Unknown Source)
	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:74)
	at org.corfudb.runtime.view.SequencerView.nextToken(SequencerView.java:27)
	at org.corfudb.runtime.view.StreamsView.acquireAndWrite(StreamsView.java:101)
	at org.corfudb.runtime.view.StreamsView.write(StreamsView.java:81)
	at com.yahoo.ycsb.db.CorfuClient.insert(CorfuClient.java:181)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:208)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:793)

**Comment by no2chem** [comment]
Hi Ohad,

I suspect that the source of this bug is from the RPC layer of Corfu.
Documentation of the RPC layer can be found here: https://github.com/CorfuDB/CorfuDB/wiki/RPC-framework

Some initial debugging with JProfiler suggests that for some reason org.corfudb.util.CFUtils.failAfter is responsible for some 79% of heap allocations, this class is used for implementing timeouts, but it shouldn't be allocating anything.

**Comment by Maithem** [comment]
@no2chem can you reproduce this issue?

I tried writing 8 million entries (~4000 bytes each), but ran into "OutOfMemoryError: Java heap space".
After bumping up the heap allocation to the jvm, I was able to write all 8 million entries, so it seems like there is a memory leak, but I didn't see the NullPointerException error.

**Comment by ohadshacham** [comment]
Hi Maithem,

I sent you the YCSB client I used to reproduce the issue.

**Comment by Maithem** [comment]
Hey @ohadshacham 

Can you provide the workload file that you used.
Also, did you use our fork of ycsb or the latest version?

**Comment by ohadshacham** [comment]
Hey,

I used your fork and modified CorfuClient.java to use streams.
I emailed you the file I used.

**Comment by no2chem** [comment]
@Maithem - Ohad is probably referring to https://github.com/CorfuDB/Corfu-YCSB

**Comment by Maithem** [comment]
@ohadshacham I am using the file you sent me, but I was asking about the ycsb workload file that you used.

@no2chem 
I think I know what's wrong. I ran the benchmark with 8 billion records on a single node deployment and I can see similar failures to the one @ohadshacham  reported. I've noticed that before the client crashed there were timeout exceptions that caused the client to invalidate the layout view a couple of times. I profiled the server's jvm and it seems that objects are being created at a rate faster than the heap growth rate. As a consequence, the gc was constantly being triggered which caused the client to timeout (because of the long pauses).

It seems like we have two issues:
1. A memory leak. For example, there are much more longs (presumably for addresses) allocated than the number of log entries which are not being garbage collected

2. The client somehow reaches a state where the layout view is "bad". I'm still investigating whether the client incorrectly handles timeouts when it's requesting the layout from the layout server, or if the layout server is replying with "bad" information

While we fix those two issues, you can use the following workaround:
Set the jvm's Xms parameter to be the same as Xmx or run the layout server on a different node.


@ohadshacham 
Also, can you confirm the following: did you see any timeouts before the crash and were you running everything on a single node?

**Comment by ohadshacham** [comment]
Thanks @Maithem The sequencer, the layout server and one of the log servers are located on a single node. The client is located on another. It also occurs when I used stripes/replicas on different servers.
I didn't noticed if there were any timeouts. I'll check it out. 

Thanks for the workaround I'll check it out. I assume that currently the gc degrades performance significantly.

**Comment by Maithem** [comment]
@ohadshacham np

@no2chem I think we have some concurrency issues in the corfu run-time object, it is not thread safe.
Different threads are accessing shared object members that are not declared as volatile, so sometimes garbage values are being accessed (i.e. null).

I have a fix, but can't write a good test for it. I can't find a good way of writing a reliable test that can detect this or similar concurrency issues. Anyways, below is my output from running

/bin/ycsb load corfu -P workloads/workloada &> out.log &

[OVERALL], RunTime(ms), 3969078.0
[OVERALL], Throughput(ops/sec), 2519.476815522396
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 2.0
[CLEANUP], MinLatency(us), 2.0
[CLEANUP], MaxLatency(us), 2.0
[CLEANUP], 95thPercentileLatency(us), 2.0
[CLEANUP], 99thPercentileLatency(us), 2.0
[INSERT], Operations, 1.0E7
[INSERT], AverageLatency(us), 394.6120441
[INSERT], MinLatency(us), 281.0
[INSERT], MaxLatency(us), 1.0018815E7
[INSERT], 95thPercentileLatency(us), 524.0
[INSERT], 99thPercentileLatency(us), 693.0
[INSERT], Return=OK, 10000000
