### ISSUE TITLE
Wrong epoch number used by "corfu_stream write"

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#142]
Based on master branch at commit 73b86f1158c4fa112b36da7e6c812ae5b916a587

Steps to reproduce:

    cd /path/to/top/of/CorfuDB
    mvn install
    ./bin/corfu_server -l /tmp/buggy -a localhost -t -1 -d INFO 8000 &
    sleep 3
    ./bin/corfu_layout corfu_layout bootstrap -l /tmp/test.1 localhost:8000
    echo Hello, world | ./bin/corfu_stream corfu_stream write -c localhost:8000 -i test

... where the contents of the bootstrap config file `/tmp/test.1` bootstraps this single node into epoch 7.

    {
        "layoutServers": [ "localhost:8000" ],
        "sequencers": [ "localhost:8000" ],
        "segments": [
    	{
    	    "replicationMode": "CHAIN_REPLICATION",
    	    "start": 0,
    	     "end": -1,
    	     "stripes": [
    		 {
    		     "logServers": [ "localhost:8000" ]
    		 }
    	     ]}],
        "epoch": 7
    }
    
The error observed by the client:

    18:14:26.576 INFO  [main] o.c.r.CorfuRuntime - Connecting to Corfu server instance, layout servers=[localhost:8000]
    18:14:26.822 ERROR [main] o.c.c.corfu_stream - Exception
    org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]
    	at org.corfudb.runtime.clients.NettyClientRouter.validateEpochAndClientID(NettyClientRouter.java:347) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at org.corfudb.runtime.clients.NettyClientRouter.channelRead0(NettyClientRouter.java:365) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at org.corfudb.runtime.clients.NettyClientRouter.channelRead0(NettyClientRouter.java:35) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:283) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
    	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
    RuntimeException exception: org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=0]

Also, there's an error logged by the server, also.  This is not a feature.  `^_^`

    18:14:26.742 INFO  [accept-0] i.n.h.l.LoggingHandler - [id: 0x70c5b3fa, L:/0:0:0:0:0:0:0:0:8000] RECEIVED: [id: 0xcc9cbbf3, L:/127.0.0.1:8000 - R:/127.0.0.1:50276]
    18:14:26.822 ERROR [event-1] o.c.i.NettyServerRouter - Error in handling inbound message, {}
    io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
            at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:50) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
            at org.corfudb.protocols.wireprotocol.CorfuMsg.release(CorfuMsg.java:174) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
            at org.corfudb.infrastructure.NettyServerRouter.channelRead(NettyServerRouter.java:129) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277) [corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264) [corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:283) [corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [corfu-0.1-SNAPSHOT-shaded.jar:na]
            at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [corfu-0.1-SNAPSHOT-shaded.jar:na]
            at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by no2chem** [comment]
The netty bug was fixed by #149. Checking the first part of this bug.

**Comment by no2chem** [comment]
I see. The problem is that the layout client in epoch 0 doesn't want to accept a message from the layout server in epoch 7. Working on it.

**Comment by no2chem** [comment]
It also turns out the unit testing framework doesn't bother validating the epoch. Adding that as well, will probably expose more bugs.

**Comment by no2chem** [comment]
May be fixed by #154

**Comment by slfritchie** [comment]
Not reproducable at master branch commit 232d8116df571110f865804754e2002def1e1f91, closing.
