### ISSUE TITLE
Layout change permits backward epoch

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#146]
In master branch at commit ee47f10ea05dcadb68ef9d7dd571510034b1ea6a

I confess I'm not quite sure where sanity checking is supposed to be done, but if there's supposed to be sanity checking by the `corfu_layout` cmdlet, it isn't being done.  (There's probably quite a bit of other sanity checking missing also?)  The following script will cause the layout epoch to go from 0 -> 2 -> 1.

Usage: `rm -f /tmp/foo ; sh -x /path/to/script > /tmp/foo 2>&1 ; grep '"epoch"' /tmp/foo | grep -v sed`

Output:

    $ rm -f /tmp/foo ; sh -x ~/foo5 > /tmp/foo 2>&1 ; grep '"epoch"' /tmp/foo | grep -v sed
      "epoch": 0
      "epoch": 2
      "epoch": 1

Script:

    ./bin/corfu_server -ms 8000 > /dev/null 2>&1 &
    spid0=$!
    sleep 1
    ./bin/corfu_layouts corfu_layouts query -c localhost:8000 2>&1 | grep epoch
    
    cat<<! > /tmp/buggy.config2
    {
        "layoutServers": [ "localhost:8000"
                         ],
        "sequencers": [ "localhost:8000" ],
        "segments": [
        {
            "replicationMode": "CHAIN_REPLICATION",
            "start": 0,
             "end": -1,
             "stripes": [
             {
                 "logServers": [ "localhost:8000" ]
             }
             ]}],
        "epoch": 2
    }
    !
    
    RANK=1
    ./bin/corfu_layout corfu_layout prepare localhost:8000 -r $RANK
    ./bin/corfu_layout corfu_layout propose localhost:8000 -r $RANK -l /tmp/buggy.config2
    ./bin/corfu_layout corfu_layout committed localhost:8000 -r $RANK
    
    sleep 1
    ./bin/corfu_layouts corfu_layouts query -c localhost:8000 2>&1 | grep epoch
    
    sed 's/"epoch": 2/"epoch": 1/' < /tmp/buggy.config2 > /tmp/buggy.config1
    RANK=2
    ./bin/corfu_layout corfu_layout prepare localhost:8000 -r $RANK
    ./bin/corfu_layout corfu_layout propose localhost:8000 -r $RANK -l /tmp/buggy.config1
    ./bin/corfu_layout corfu_layout committed localhost:8000 -r $RANK
    
    sleep 1
    ./bin/corfu_layouts corfu_layouts query -c localhost:8000 2>&1 | grep epoch
    
    pkill -P $spid0

**Comment by slfritchie** [comment]
On today's master branch at commit cbf5f57ce11a7765c6e27bdc25dbfba1a15a4db6, the behavior has changed.  See gist at https://gist.github.com/slfritchie/cec198a2ad7a45c3585c2091c6f10464 for an updated test script.

Today's behavior has line 33's `./bin/corfu_layout committed localhost:8000 -r $RANK=1` failing with the exception:

    Exception during prepare
    org.corfudb.runtime.exceptions.WrongEpochException: Wrong epoch. [expected=22]
            at org.corfudb.runtime.clients.NettyClientRouter.validateEpochAndClientID(NettyClientRouter.java:371) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
            at org.corfudb.runtime.clients.NettyClientRouter.channelRead0(NettyClientRouter.java:389) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]

... which is very helpful.  It could also be useful to have the `propose` phase perform the same check.
