### ISSUE TITLE
IllegalReferenceCountException on a call to open to build an object with same stream name.

### ISSUE THREAD

**Issue by GirishMururu** [CorfuDB/CorfuDB#152]
Have a call to build corfuobject with open() call as follows

```
getRuntime().getObjectsView().build()
                .setStreamName("mystream")
                .setType(myclass.class)
                .open();

```

It works fine for the first time. Stop the process. Run it again without restarting the corfu server.  It crashes with Illegal Reference count Exception as follows

```
 Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
io.netty.util.IllegalReferenceCountException: refCnt: 0
    at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1190)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1176)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:587)
    at org.corfudb.util.serializer.CorfuSerializer.deserialize(CorfuSerializer.java:40)
    at org.corfudb.protocols.wireprotocol.LogUnitPayloadMsg.getPayload(LogUnitPayloadMsg.java:39)
    at org.corfudb.protocols.wireprotocol.LogUnitReadResponseMsg$ReadResult.getPayload(LogUnitReadResponseMsg.java:91)
    at org.corfudb.runtime.view.StreamView.read(StreamView.java:291)
    at org.corfudb.runtime.object.CorfuProxyBuilder.getProxy(CorfuProxyBuilder.java:219)
    at org.corfudb.runtime.view.ObjectBuilder.lambda$open$0(ObjectBuilder.java:78)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
    at org.corfudb.runtime.view.ObjectBuilder.open(ObjectBuilder.java:76)
```

If we run again after restarting the server it works fine again for the first time and crashes on repeat.

**Comment by no2chem** [comment]
Hi Girish,

I'm trying to build a unit test which replicates the issue that you're getting. Could you tell me a little bit more about myclass? Thanks.

**Comment by GirishMururu** [comment]
```
public class myclass implements ICorfuSMRObject<myclass> {
	AtomicInteger counter = new AtomicInteger(0);
	int Sum;
        //constructor
           public myclass(){}
      @MutatorAccesor
         public bool f1(){}
      @MutatorAccesor
         public bool f2(){}
}

```
this is what myclass looks like in my code.

**Comment by no2chem** [comment]
Hm, why does your class implement ICorfuSMRObject? Try removing that.

**Comment by GirishMururu** [comment]
Without implementing  ICorfuSMRObject the problem still exists and also the corfu runtime throws too many exceptions when myclass does not implement ICorfuSMRObject.

**Comment by no2chem** [comment]
To be clear, your object is not supposed to implement ICorfuSMRObject unless it also implements getSMRObject. Can you tell me what exceptions the runtime throws?

**Comment by GirishMururu** [comment]
Can you give a brief explanation of what the different values in the below interface stands for?
 
```
public @interface CorfuObject {
    ConstructorType constructorType() default ConstructorType.RUNTIME;
    ObjectType objectType() default ObjectType.STATELESS;
    StateSource stateSource() default StateSource.SELF;
    Class stateType() default StaticMappingObject.class;
}
```

I am seeing different types of failures by changing these values for myclass without implementing ICorfuSMRObject.

**Comment by no2chem** [comment]
Sure, 

constructor type determines whether the constructor is persisted in the log
objecttype determines whether or not it uses the SMR infrastructure
statesource determines whether the state comes from the object itself or whether it comes from getSMRObject()
statetype just determines the class that the getSMRObject returns

But why don't you try not annotating the object you are using with anything and see if it works? Be sure to pull the latest changes.

**Comment by GirishMururu** [comment]
After checking out master CorfuDB today(06-22-2016),  i get the following error when i call the method f1() of myclass  without implementing ICorfuSMRObject. 

```
ERROR org.corfudb.runtime.object.CorfuSMRObjectProxy  Couldn't dispatch method f1() during apply update [pool-1-thread-3]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.corfudb.runtime.object.CorfuSMRObjectProxy.applySMRUpdate(CorfuSMRObjectProxy.java:374)
	at org.corfudb.runtime.object.CorfuSMRObjectProxy.applyUpdate(CorfuSMRObjectProxy.java:411)
	at org.corfudb.runtime.object.CorfuSMRObjectProxy.lambda$8(CorfuSMRObjectProxy.java:459)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.corfudb.runtime.object.CorfuSMRObjectProxy.sync(CorfuSMRObjectProxy.java:459)
	at org.corfudb.runtime.object.CorfuSMRObjectProxy.interceptMutatorAccessor(CorfuSMRObjectProxy.java:262)
	
	... 50 more
```

**Comment by no2chem** [comment]
You need 
@CorfuObject(objectType= ObjectType.SMR,
        constructorType= ConstructorType.PERSISTED,
        stateSource = StateSource.SELF
)

**Comment by no2chem** [comment]
#157 adds an example in a unit test verifying the functionality of the annotation framework.

**Comment by GirishMururu** [comment]
I made changes similar to your example, however it does not persist an update from other threads. All threads always return one from 
`a1.incrementandget() `

**Comment by no2chem** [comment]
Hi Girish, are you calling incrementAndGet directly, or did you add a function that calls incrementandget?

It's critical that you implement a function that calls a1, rather than calling a1 directly. You should treat all class variables as private as the object layer isn't able to instrument them due to Java limitations.

**Comment by GirishMururu** [comment]
I did not call directly, i had a function. Can you change the test case to verify if it persists previous value. A1.incrementandget () !=0 might not be sufficient.

**Comment by no2chem** [comment]
It appears that there is a bug in the annotation framework.

Again, does your test work fine if you REMOVE the annotation and also not implement ISMRCorfuObject?

**Comment by GirishMururu** [comment]
No, without the annotation and  not implementing ISMRCorfuObject, i get the 

> Couldn't dispatch method f1() during apply update

It fails at  line number 374 in CorfuSMRObjectProxy.java and within that at line number 498 in method.class
```
// Execute the SMR command
            Object ret = m.invoke(obj, entry.getSMRArguments());
```

**Comment by no2chem** [comment]
is f1 marked public?

**Comment by GirishMururu** [comment]
yes

**Comment by no2chem** [comment]
Ok, not sure why you're getting that error, I'll look into it. Is the class marked public as well?

For now, try pulling the latest, as #159 fixes the bug in the annotation framework.

**Comment by GirishMururu** [comment]
Yeah with the fix it works with annotation and without implementing ISMRCorfuObject. However the original issue of illegalreferencecountexception still remains. Now i looked at the exception stack and the first client gives  java.lang.NullPointerException and below stack while others throw illegalreferencecountexception
```
	at org.corfudb.protocols.logprotocol.LogEntry.deserialize(LogEntry.java:82)
	at org.corfudb.util.serializer.CorfuSerializer.deserialize(CorfuSerializer.java:46)
	at org.corfudb.protocols.wireprotocol.LogUnitPayloadMsg.getPayload(LogUnitPayloadMsg.java:39)
	at org.corfudb.protocols.wireprotocol.LogUnitReadResponseMsg$ReadResult.getPayload(LogUnitReadResponseMsg.java:91)
	at org.corfudb.runtime.view.StreamView.read(StreamView.java:291)
	at org.corfudb.runtime.object.CorfuProxyBuilder.getProxy(CorfuProxyBuilder.java:239)
	at org.corfudb.runtime.view.ObjectBuilder.lambda$0(ObjectBuilder.java:78)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.corfudb.runtime.view.ObjectBuilder.open(ObjectBuilder.java:76)
```

**Comment by slfritchie** [comment]
I hope y'all don't mind if I close this old issue.  The code in the original report will still throw a null pointer exception, just in a different place.  The practice in today's code is to call the `CorfuRuntime`'s `.connect()` method prior to using `.getObjectsView()`.

Here's the Clojure version:

    $ bin/shell
    [... startup stuff omitted]
    
    org.corfudb.shell=> (get-runtime "localhost:8000")
    #object[org.corfudb.runtime.CorfuRuntime 0x6247edab "org.corfudb.runtime.CorfuRuntime@6247edab"]
    org.corfudb.shell=> (.connect *r)
    17:20:15.498 INFO  [nREPL-worker-0] o.c.r.CorfuRuntime - Connecting to Corfu server instance, layout servers=[localhost:8000]
     #object[org.corfudb.runtime.CorfuRuntime 0x6247edab "org.corfudb.runtime.CorfuRuntime@6247edab"]
    org.corfudb.shell=> (def m (.. *r getObjectsView build (setType org.corfudb.runtime.collections.FGMap) (setStreamName "mystream2") open))
    #'org.corfudb.shell/m
    org.corfudb.shell=> (.put m "some-key" 42)
    nil
    org.corfudb.shell=> (.get m "some-key")
    42
    org.corfudb.shell=> (.get m "other key")
    nil
    org.corfudb.shell=> 

Without the `connect()` method call, the `open()` at the end of the 2nd line's chain throws an exception.

    org.corfudb.shell=> (get-runtime "localhost:8000")
    #object[org.corfudb.runtime.CorfuRuntime 0x6247edab "org.corfudb.runtime.CorfuRuntime@6247edab"]
    org.corfudb.shell=> (def m (.. *r getObjectsView build (setType org.corfudb.runtime.collections.FGMap) (setStreamName "mystream2") open))
    
    NullPointerException   org.corfudb.runtime.view.AbstractView.layoutHelper (AbstractView.java:69)
    org.corfudb.shell=> *e
    #error {
     :cause nil
     :via
     [{:type clojure.lang.Compiler$CompilerException
       :message "java.lang.NullPointerException, compiling:(NO_SOURCE_FILE:1:1)"
       :at [clojure.lang.Compiler$DefExpr eval "Compiler.java" 464]}
      {:type java.lang.NullPointerException
       :message nil
       :at [org.corfudb.runtime.view.AbstractView layoutHelper "AbstractView.java" 69]}]
     :trace
     [[org.corfudb.runtime.view.AbstractView layoutHelper "AbstractView.java" 69]
      [org.corfudb.runtime.view.SequencerView nextToken "SequencerView.java" 33]
      [org.corfudb.runtime.view.StreamView check "StreamView.java" 147]
      [org.corfudb.runtime.object.CorfuProxyBuilder getProxy "CorfuProxyBuilder.java" 210]
      [org.corfudb.runtime.view.ObjectBuilder lambda$open$0 "ObjectBuilder.java" 87]
      [java.util.concurrent.ConcurrentHashMap computeIfAbsent "ConcurrentHashMap.java" 1660]
      [org.corfudb.runtime.view.ObjectBuilder open "ObjectBuilder.java" 85]
      [sun.reflect.NativeMethodAccessorImpl invoke0 "NativeMethodAccessorImpl.java" -2]
      [sun.reflect.NativeMethodAccessorImpl invoke "NativeMethodAccessorImpl.java" 62]
      [sun.reflect.DelegatingMethodAccessorImpl invoke "DelegatingMethodAccessorImpl.java" 43]
      [java.lang.reflect.Method invoke "Method.java" 498]
      [clojure.lang.Reflector invokeMatchingMethod "Reflector.java" 93]
    ... lots of Clojure-related stack omitted ....
