### ISSUE TITLE
CorfuTable constructor called twice on open

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#1524]
## Overview

While looking into the format of a log message realized that by executing:

CorfuTable<String, String>
                corfuTable = getDefaultRuntime().getObjectsView().build()
                .setTypeToken(new TypeToken<CorfuTable<String, String>>() {})
                .setStreamName("test")
                .open();

The CorfuTable constructor is called twice, meaning we are creating two new instances. This is the actual stack trace for both calls:

**First Time:**

`	at org.corfudb.runtime.collections.CorfuTable.<init>(CorfuTable.java:291)
	at org.corfudb.runtime.collections.CorfuTable.<init>(CorfuTable.java:302)
	at org.corfudb.runtime.collections.CorfuTable$CORFUSMR.<init>(CorfuTable$CORFUSMR.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.corfudb.runtime.object.CorfuCompileWrapperBuilder.getWrapper(CorfuCompileWrapperBuilder.java:44)
	at org.corfudb.runtime.view.ObjectBuilder.lambda$open$0(ObjectBuilder.java:109)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.corfudb.runtime.view.ObjectBuilder.open(ObjectBuilder.java:107)
	at org.corfudb.runtime.collections.CorfuTableTest.cannotLookupByIndexAndFilterWhenIndexNotSpecified(CorfuTableTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.corfudb.AbstractCorfuTest$1$1.lambda$evaluate$0(AbstractCorfuTest.java:105)
	at java.lang.Thread.run(Thread.java:745)`

**Second Time:**

`	at org.corfudb.runtime.collections.CorfuTable.<init>(CorfuTable.java:291)
	at org.corfudb.runtime.collections.CorfuTable.<init>(CorfuTable.java:302)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.corfudb.runtime.object.CorfuCompileProxy.getNewInstance(CorfuCompileProxy.java:442)
	at org.corfudb.runtime.object.VersionLockedObject.<init>(VersionLockedObject.java:145)
	at org.corfudb.runtime.object.CorfuCompileProxy.<init>(CorfuCompileProxy.java:147)
	at org.corfudb.runtime.object.CorfuCompileWrapperBuilder.getWrapper(CorfuCompileWrapperBuilder.java:67)
	at org.corfudb.runtime.view.ObjectBuilder.lambda$open$0(ObjectBuilder.java:109)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.corfudb.runtime.view.ObjectBuilder.open(ObjectBuilder.java:107)
	at org.corfudb.runtime.collections.CorfuTableTest.cannotLookupByIndexAndFilterWhenIndexNotSpecified(CorfuTableTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.corfudb.AbstractCorfuTest$1$1.lambda$evaluate$0(AbstractCorfuTest.java:105)
	at java.lang.Thread.run(Thread.java:745)`

This needs to be further looked into.

**Comment by Maithem** [comment]
I'm thinking about a clean way of fixing this. #1484

**Comment by Maithem** [comment]
Please close this issue, if it is not the same as #1484

**Comment by Maithem** [comment]
@WenbinZhu can you make sure that this issue is the same as #1484 and then close this, if they are?

**Comment by WenbinZhu** [comment]
@Maithem I think they are not same. We treat no-argument constructor differently from parameterized constructor. And  this issue is because we created two instances on purpose, which is irrelevant of whether the constructor called has parameters. #1484 is more specific on calling the constructor with parameters, which I haven't observed the problem for now.

**Comment by Maithem** [comment]
The proxy creates an object to use with the code that is generated from the annotation processor and the VLO creates another object that holds the state. This is expected.
