### ISSUE TITLE
NullPointerException in ClusterGraph

### ISSUE THREAD

**Issue by zalokhan** [CorfuDB/CorfuDB#1764]
## Overview

Noticed the following exception in addAdnRemoveNodeIT.

```
2019-02-28T18:10:48.159Z | ERROR |              DetectionWorker-1 |  o.c.i.RemoteMonitoringService | Exception invoking failure handler : {}
java.lang.NullPointerException: null
	at org.corfudb.infrastructure.management.failuredetector.ClusterGraph.lambda$null$0(ClusterGraph.java:112)
	at com.google.common.collect.ImmutableSet$Indexed.forEach(ImmutableSet.java:394)
	at org.corfudb.infrastructure.management.failuredetector.ClusterGraph.lambda$toSymmetric$1(ClusterGraph.java:107)
	at com.google.common.collect.ImmutableSet$Indexed.forEach(ImmutableSet.java:394)
	at org.corfudb.infrastructure.management.failuredetector.ClusterGraph.toSymmetric(ClusterGraph.java:95)
	at org.corfudb.infrastructure.management.CompleteGraphAdvisor.failedServer(CompleteGraphAdvisor.java:63)
	at org.corfudb.infrastructure.RemoteMonitoringService.detectFailure(RemoteMonitoringService.java:507)
	at org.corfudb.infrastructure.RemoteMonitoringService.lambda$runFailureDetectorTask$4(RemoteMonitoringService.java:369)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

@xnull Can you have a look at this?

**Comment by xnull** [comment]
ok

**Comment by zalokhan** [comment]
@xnull Is this addressed ?

**Comment by xnull** [comment]
It's not. I am not sure how it can happen. 
Let me think about that
