### ISSUE TITLE
Guava Cache Throwing Assertion Errors

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1878]
**Bug report.**
This failure is not expected to happen. 

`java.lang.AssertionError
        at com.google.common.cache.LocalCache$Segment.getNextEvictable(LocalCache.java:2653)
        at com.google.common.cache.LocalCache$Segment.evictEntries(LocalCache.java:2637)
        at com.google.common.cache.LocalCache$Segment.storeLoadedValue(LocalCache.java:3158)
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2316)
        at com.google.common.cache.LocalCache$Segment.compute(LocalCache.java:2250)
        at com.google.common.cache.LocalCache.compute(LocalCache.java:4196)
        at com.google.common.cache.LocalCache.computeIfAbsent(LocalCache.java:4203)
        at org.corfudb.runtime.view.AddressSpaceView.read(AddressSpaceView.java:254)
        at org.corfudb.runtime.view.stream.BackpointerStreamView.read(BackpointerStreamView.java:214)
        at org.corfudb.runtime.view.stream.BackpointerStreamView.followBackpointers(BackpointerStreamView.java:322)
        at org.corfudb.runtime.view.stream.BackpointerStreamView.fillReadQueue(BackpointerStreamView.java:532)
        at org.corfudb.runtime.view.stream.AbstractQueuedStreamView.getNextEntries(AbstractQueuedStreamView.java:136)
        at org.corfudb.runtime.view.stream.AbstractQueuedStreamView.getNextEntries(AbstractQueuedStreamView.java:40)
        at org.corfudb.runtime.view.stream.AbstractContextStreamView.remainingUpTo(AbstractContextStreamView.java:164)
        at org.corfudb.runtime.view.stream.ThreadSafeStreamView.remainingUpTo(ThreadSafeStreamView.java:89)
        at org.corfudb.runtime.view.stream.IStreamView.remaining(IStreamView.java:170)`

**Comment by WenbinZhu** [comment]
Maybe we can open an issue in Guava's  repo and ask the maintainers about this AssertionError to save some time?

**Comment by Maithem** [comment]
@WenbinZhu I will do that, first I'm trying to reproduce it.

**Comment by Maithem** [comment]
Already opened an issue on their repo
https://github.com/google/guava/issues/3464

**Comment by ben-manes** [comment]
I believe if you upgrade to Caffeine 2.7, then you can use it instead. The switch to Guava was, I believe, because this workload is more LRU than LFU. The adaptive policy should make Caffeine competitive here. Guava's compute methods are known to be buggy.

**Comment by xnull** [comment]
@Maithem I agree with Ben, but also, Ben the problem is that we can't reproduce the bug in our tests. I tried to get the issue by writing and reading the cache by many threads and the cache worked correctly. https://github.com/CorfuDB/CorfuDB/blob/6fcef585f5fd96c72604418617fce6d112868e06/runtime/src/test/java/org/corfudb/runtime/view/AddressSpaceViewCacheTest.java#L89

The problem is - we can't just say: ok, Guava's compute methods are known to be buggy let's replace it by caffeine. 
We need to reproduce the issue in our tests, then we can come up with a solution

**Comment by ben-manes** [comment]
Sorry, I very much agree with writing tests to demonstrate and fix the bug upstream. I merely meant to inform that the issue in Caffeine was addressed.

Guava doesn’t work correctly in conjunction with its own loading methods, which is a bug that I’ve reported. I’ll have to review your case and maybe can dream up a test case.

**Comment by ben-manes** [comment]
I can't reproduce this assertion error, but rather a different failure where a phantom null value is observed.

```
Failed: key 14 on operation com.github.benmanes.caffeine.cache.MultiThreadedTest$$Lambda$2/133250414@428a5136
com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key 14.
	at com.google.common.cache.LocalCache$Segment.waitForLoadingValue(LocalCache.java:2176)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2038)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at com.github.benmanes.caffeine.cache.testing.GuavaCacheFromContext$GuavaCache.get(GuavaCacheFromContext.java:153)
	at com.github.benmanes.caffeine.cache.MultiThreadedTest.lambda$1(MultiThreadedTest.java:59)
	at com.github.benmanes.caffeine.testing.Threads$Thrasher.run(Threads.java:149)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.github.benmanes.caffeine.testing.ConcurrentTestHarness.lambda$0(ConcurrentTestHarness.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xnull** [comment]
Hmm, interesting, would you mind showing MultiThreadedTest source code?

BTW, just wondering, what way do you use in caffeine to find all that kind of bugs (like this one) and guarantee consistency and correct behavior of the cache?

**Comment by ben-manes** [comment]
I hacked up [this class](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/MultiThreadedTest.java) and the [Guava adapter](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/testing/GuavaCacheFromContext.java) quite a bit, and used your settings at 1ms durations.

In this test case it just thrashes the cache enough times to see if anything breaks. Other tests are more explicit, but most are not concurrent. I use a listener after a test run to inspect the internal state for corruption, which caught the majority of problems in Caffeine. A lot of testing is brute force of many cases and every configuration option. Still, things get missed and I investigate bugs when found.

**Comment by ben-manes** [comment]
I think that I reproduced a bug that I had previously reported (https://github.com/google/guava/issues/2827). In this case I was using `Cache.get(key, callable)` which wraps the `Callable` as a `CacheLoader` to invoke that flow. I also had `Map.compute(key, (k, v) -> v)` which could result in a `null` if the entry didn't exist. Because a compute can return null while a load method cannot, the interaction when a loader waits for a computation to finish is not handled correctly. In Caffeine we don't have this problem partially because we allow a null response from the loader, so the semantics are identical (and map to common methods).

**Comment by Maithem** [comment]
the problem disappeared after I removed the `asMap()` interface calls. Closing this issue, the guava bug is still open at google/guava#2827
