### ISSUE TITLE
CI Failing

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#1890]
**Bug report.**
PR #1802 broke CI for the master branch. It seems like the package phase is not being called before the integration tests run. 

```
Caused by: com.spotify.docker.client.exceptions.ImageNotFoundException: Image not found: corfudb/corfu-server:0.2.3-10995
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:727)
	at org.corfudb.universe.node.server.docker.DockerCorfuServer.deployContainer(DockerCorfuServer.java:297)
	... 6 more
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/create?name=ezhxhm-corfu-node34239: 404, body: {"message":"No such image: corfudb/corfu-server:0.2.3-10995"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2820)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2703)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:722)
	... 7 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1008)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at com.spotify.docker.client.shaded.org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```

**Comment by xnull** [comment]
Will fix today
