### ISSUE TITLE
NPE in RemoteMonitoringService::runDetectionTasks 

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#2035]
## Overview

I just saw a NullPointerException in RemoteMonitoringService::runDetectionTasks:

```
2019-07-05T01:15:52.810Z | INFO  |       initializationTaskThread |          o.c.i.RecoveryHandler | Recovery layout epoch:386, Cluster epoch: 387
2019-07-05T01:15:52.814Z | INFO  |       initializationTaskThread |            o.c.i.ServerContext | saveManagementLayout: Updated to new layout at epoch 387
2019-07-05T01:15:52.814Z | INFO  |       initializationTaskThread |          o.c.i.ManagementAgent | initializationTask: Recovery completed
2019-07-05T01:15:52.814Z | INFO  |       initializationTaskThread |  o.c.i.RemoteMonitoringService | Trigger sequencer bootstrap on startup
2019-07-05T01:15:52.817Z | INFO  |              DetectionWorker-0 |   o.c.r.v.LayoutManagementView | triggerSequencerBootstrap: a bootstrap task is triggered.
2019-07-05T01:15:52.838Z | DEBUG |                      worker-11 | c.p.w.NettyCorfuMessageEncoder | encode: New max write buffer found 462
2019-07-05T01:15:52.847Z | DEBUG |                 CorfuRuntime-0 | o.corfudb.runtime.CorfuRuntime | Trying connection to layout server 10.108.112.216:9000
2019-07-05T01:15:52.850Z | DEBUG |                 CorfuRuntime-0 | o.corfudb.runtime.CorfuRuntime | Layout server 10.108.112.216:9000 responded with layout Layout(layoutServers=[10.108.112.215:9000, 10.108.112.216:9000, 10.108.112.217:9000], sequencers=[10.108.112.217:9000, 10.108.112.216:9000, 10.108.112.215:9000], segments=[Layout.LayoutSegment(replicationMode=CHAIN_REPLICATION, start=0, end=-1, stripes=[Layout.LayoutStripe(logServers=[10.108.112.215:9000, 10.108.112.217:9000, 10.108.112.216:9000])])], unresponsiveServers=[], epoch=387, clusterId=bec87bad-e553-458e-9d6b-301897555fa2)
2019-07-05T01:15:52.851Z | ERROR |              ManagementService |   org.corfudb.util.LambdaUtils | runSansThrow: Suppressing exception while executing runnable: 
java.lang.NullPointerException: null
	at org.corfudb.infrastructure.RemoteMonitoringService.runDetectionTasks(RemoteMonitoringService.java:289)
	at org.corfudb.util.LambdaUtils.runSansThrow(LambdaUtils.java:172)
	at org.corfudb.infrastructure.RemoteMonitoringService.lambda$start$0(RemoteMonitoringService.java:201)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This happens after server restart and management agent recovered its layout.
 @xnull Can you take a look?

**Comment by xnull** [comment]
https://github.com/CorfuDB/CorfuDB/pull/2036
