### ISSUE TITLE
java.lang.reflect.InvocationTargetException during parallel test case

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#212]
Using commit cce7c97ced3b23c85b5371e0359bd09af8bc0226 of https://github.com/slfritchie/CorfuDB/tree/slf/eqc-layout-hack6c ... which is based on the `master` branch of the main CorfuDB repo as of Aug 17 (after Medhavi's work was merged).

```
C11 = [{[{init,{state,[115,98,98,53,58,56,48,48,48],[cmdlet0,cmdlet1,cmdlet2,cmdlet3,cmdlet4,cmdlet5,cmdlet6,cmdlet7,cmdlet8,cmdlet9],false,42,[]}},{set,{var,1},{call,smrmap_qc,reset,[{cmdlet6,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48]]}},{set,{var,2},{call,smrmap_qc,containsValue,[{cmdlet8,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,[72,101,108,108,111,45,119,111,114,108,100,33]]}},{set,{var,3},{call,smrmap_qc,containsValue,[{cmdlet0,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,[65,110,111,116,104,101,114,45,118,97,108,117,101]]}},{set,{var,4},{call,smrmap_qc,keySet,[{cmdlet0,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42]}},{set,{var,5},{call,smrmap_qc,size,[{cmdlet8,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42]}},{set,{var,6},{call,smrmap_qc,put,[{cmdlet1,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,[97],[72,101,108,108,111,45,119,111,114,108,100,33]]}},{set,{var,7},{call,smrmap_qc,remove,[{cmdlet9,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,[99]]}},{set,{var,8},{call,smrmap_qc,put,[{cmdlet8,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,[107],[65,110,111,116,104,101,114,45,118,97,108,117,101]]}}],[[{set,{var,9},{call,smrmap_qc,put,[{cmdlet0,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42,[97],[72,101,108,108,111,45,119,111,114,108,100,33]]}}],[{set,{var,10},{call,smrmap_qc,entrySet,[{cmdlet2,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42]}}],[{set,{var,11},{call,smrmap_qc,values,[{cmdlet9,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42]}}],[{set,{var,12},{call,smrmap_qc,isEmpty,[{cmdlet1,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42]}},{set,{var,13},{call,smrmap_qc,size,[{cmdlet6,'corfu-8000@sbb5'},[115,98,98,53,58,56,48,48,48],42]}}]]}].
[true = eqc:check(eqc:testing_time(5*60,smrmap_qc:prop_parallel()), C11) || _ <- lists:seq(1,30)].
```

Output:

```
Failed! 
{[{init,{state,"sbb5:8000",
               [cmdlet0,cmdlet1,cmdlet2,cmdlet3,cmdlet4,cmdlet5,cmdlet6,
                cmdlet7,cmdlet8,cmdlet9],
               false,42,[]}},
  {set,{var,1},
       {call,smrmap_qc,reset,[{cmdlet6,'corfu-8000@sbb5'},"sbb5:8000"]}},
  {set,{var,2},
       {call,smrmap_qc,containsValue,
             [{cmdlet8,'corfu-8000@sbb5'},"sbb5:8000",42,"Hello-world!"]}},
  {set,{var,3},
       {call,smrmap_qc,containsValue,
             [{cmdlet0,'corfu-8000@sbb5'},"sbb5:8000",42,"Another-value"]}},
  {set,{var,4},
       {call,smrmap_qc,keySet,[{cmdlet0,'corfu-8000@sbb5'},"sbb5:8000",42]}},
  {set,{var,5},
       {call,smrmap_qc,size,[{cmdlet8,'corfu-8000@sbb5'},"sbb5:8000",42]}},
  {set,{var,6},
       {call,smrmap_qc,put,
             [{cmdlet1,'corfu-8000@sbb5'},"sbb5:8000",42,"a","Hello-world!"]}},
  {set,{var,7},
       {call,smrmap_qc,remove,
             [{cmdlet9,'corfu-8000@sbb5'},"sbb5:8000",42,"c"]}},
  {set,{var,8},
       {call,smrmap_qc,put,
             [{cmdlet8,'corfu-8000@sbb5'},
              "sbb5:8000",42,"k","Another-value"]}}],
 [[{set,{var,9},
        {call,smrmap_qc,put,
              [{cmdlet0,'corfu-8000@sbb5'},
               "sbb5:8000",42,"a","Hello-world!"]}}],
  [{set,{var,10},
        {call,smrmap_qc,entrySet,
              [{cmdlet2,'corfu-8000@sbb5'},"sbb5:8000",42]}}],
  [{set,{var,11},
        {call,smrmap_qc,values,[{cmdlet9,'corfu-8000@sbb5'},"sbb5:8000",42]}}],
  [{set,{var,12},
        {call,smrmap_qc,isEmpty,[{cmdlet1,'corfu-8000@sbb5'},"sbb5:8000",42]}},
   {set,{var,13},
        {call,smrmap_qc,size,[{cmdlet6,'corfu-8000@sbb5'},"sbb5:8000",42]}}]]}

Sequential prefix:

   smrmap_qc:reset({cmdlet6, 'corfu-8000@sbb5'}, "sbb5:8000") -> ["OK"]
   smrmap_qc:containsValue({cmdlet8, 'corfu-8000@sbb5'}, "sbb5:8000", 42,
       "Hello-world!") ->
     ["OK", "false"]
   smrmap_qc:containsValue({cmdlet0, 'corfu-8000@sbb5'}, "sbb5:8000", 42,
       "Another-value") ->
     ["OK", "false"]
   smrmap_qc:keySet({cmdlet0, 'corfu-8000@sbb5'}, "sbb5:8000", 42) ->
     ["OK", "[]"]
   smrmap_qc:size({cmdlet8, 'corfu-8000@sbb5'}, "sbb5:8000", 42) -> ["OK", "0"]
   smrmap_qc:put({cmdlet1, 'corfu-8000@sbb5'}, "sbb5:8000", 42, "a",
       "Hello-world!") ->
     ["OK"]
   smrmap_qc:remove({cmdlet9, 'corfu-8000@sbb5'}, "sbb5:8000", 42, "c") -> ["OK"]
   smrmap_qc:put({cmdlet8, 'corfu-8000@sbb5'}, "sbb5:8000", 42, "k",
       "Another-value") ->
     ["OK"]

Parallel:

1. smrmap_qc:put({cmdlet0, 'corfu-8000@sbb5'}, "sbb5:8000", 42, "a",
    "Hello-world!") ->
  ["OK", "Hello-world!"]
2. smrmap_qc:entrySet({cmdlet2, 'corfu-8000@sbb5'}, "sbb5:8000", 42) ->
  ["OK", "[a=Hello-world!, k=Another-value]"]
3. smrmap_qc:values({cmdlet9, 'corfu-8000@sbb5'}, "sbb5:8000", 42) ->
  ["ERROR",
   "Couldn't invoke method on object: java.lang.reflect.InvocationTargetException",
   "stack: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.corfudb.cmdlets.corfu_smrobject.main2(corfu_smrobject.java:173)\n\tat org.corfudb.cmdlets.CmdletRouter.main2(CmdletRouter.java:54)\n\tat org.corfudb.infrastructure.LayoutServer.runErlMbox(LayoutServer.java:873)\n\tat org.corfudb.infrastructure.LayoutServer.runErlMbox9(LayoutServer.java:834)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(70) exceeds writerIndex(70): SlicedAbstractByteBuf(ridx: 11, widx: 70, cap: 70/70, unwrapped: UnpooledUnsafeNoCleanerDirectByteBuf(ridx: 171, widx: 171, cap: 1024))\n\tat io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1177)\n\tat io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1171)\n\tat io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:692)\n\tat io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:700)\n\tat org.corfudb.util.serializer.CorfuSerializer.deserialize(CorfuSerializer.java:31)\n\tat org.corfudb.protocols.wireprotocol.LogUnitPayloadMsg.getPayload(LogUnitPayloadMsg.java:45)\n\tat org.corfudb.protocols.wireprotocol.LogUnitReadResponseMsg$ReadResult.getPayload(LogUnitReadResponseMsg.java:117)\n\tat org.corfudb.runtime.view.StreamView.read(StreamView.java:259)\n\tat org.corfudb.runtime.view.StreamView.readTo(StreamView.java:283)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.sync(CorfuSMRObjectProxy.java:434)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.interceptAccessor(CorfuSMRObjectProxy.java:277)\n\tat org.corfudb.runtime.collections.SMRMap$ByteBuddy$U2tZvjyM.values(Unknown Source)\n\t... 8 more\n",
   "cause: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(70) exceeds writerIndex(70): SlicedAbstractByteBuf(ridx: 11, widx: 70, cap: 70/70, unwrapped: UnpooledUnsafeNoCleanerDirectByteBuf(ridx: 171, widx: 171, cap: 1024))"]
4. smrmap_qc:isEmpty({cmdlet1, 'corfu-8000@sbb5'}, "sbb5:8000", 42) ->
  ["ERROR",
   "Couldn't invoke method on object: java.lang.reflect.InvocationTargetException",
   "stack: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.corfudb.cmdlets.corfu_smrobject.main2(corfu_smrobject.java:173)\n\tat org.corfudb.cmdlets.CmdletRouter.main2(CmdletRouter.java:54)\n\tat org.corfudb.infrastructure.LayoutServer.runErlMbox(LayoutServer.java:873)\n\tat org.corfudb.infrastructure.LayoutServer.runErlMbox1(LayoutServer.java:826)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.IndexOutOfBoundsException: index: 11, length: 33685504 (expected: range(0, 70))\n\tat io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1141)\n\tat io.netty.buffer.SlicedByteBuf.slice(SlicedByteBuf.java:188)\n\tat org.corfudb.protocols.logprotocol.SMREntry.deserializeBuffer(SMREntry.java:63)\n\tat org.corfudb.protocols.logprotocol.LogEntry.deserialize(LogEntry.java:71)\n\tat org.corfudb.util.serializer.CorfuSerializer.deserialize(CorfuSerializer.java:34)\n\tat org.corfudb.protocols.wireprotocol.LogUnitPayloadMsg.getPayload(LogUnitPayloadMsg.java:45)\n\tat org.corfudb.protocols.wireprotocol.LogUnitReadResponseMsg$ReadResult.getPayload(LogUnitReadResponseMsg.java:117)\n\tat org.corfudb.runtime.view.StreamView.read(StreamView.java:259)\n\tat org.corfudb.runtime.view.StreamView.readTo(StreamView.java:283)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.sync(CorfuSMRObjectProxy.java:434)\n\tat org.corfudb.runtime.object.CorfuSMRObjectProxy.interceptAccessor(CorfuSMRObjectProxy.java:277)\n\tat org.corfudb.runtime.collections.SMRMap$ByteBuddy$uyKJrki9.isEmpty(Unknown Source)\n\t... 8 more\n",
   "cause: java.lang.IndexOutOfBoundsException: index: 11, length: 33685504 (expected: range(0, 70))"]
   smrmap_qc:size({cmdlet6, 'corfu-8000@sbb5'}, "sbb5:8000", 42) -> ["OK", "2"]

Reason: no_possible_interleaving
** exception error: no match of right hand side value false
```

Here's a prettier-printing of the Java exception.

```
stack: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.corfudb.cmdlets.corfu_smrobject.main2(corfu_smrobject.java:173)
        at org.corfudb.cmdlets.CmdletRouter.main2(CmdletRouter.java:54)
        at org.corfudb.infrastructure.LayoutServer.runErlMbox(LayoutServer.java:873)
        at org.corfudb.infrastructure.LayoutServer.runErlMbox1(LayoutServer.java:826)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: index: 11, length: 33685504 (expected: range(0, 70))
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1141)
        at io.netty.buffer.SlicedByteBuf.slice(SlicedByteBuf.java:188)
        at org.corfudb.protocols.logprotocol.SMREntry.deserializeBuffer(SMREntry.java:63)
        at org.corfudb.protocols.logprotocol.LogEntry.deserialize(LogEntry.java:71)
        at org.corfudb.util.serializer.CorfuSerializer.deserialize(CorfuSerializer.java:34)
        at org.corfudb.protocols.wireprotocol.LogUnitPayloadMsg.getPayload(LogUnitPayloadMsg.java:45)
        at org.corfudb.protocols.wireprotocol.LogUnitReadResponseMsg$ReadResult.getPayload(LogUnitReadResponseMsg.java:117)
        at org.corfudb.runtime.view.StreamView.read(StreamView.java:259)
        at org.corfudb.runtime.view.StreamView.readTo(StreamView.java:283)
        at org.corfudb.runtime.object.CorfuSMRObjectProxy.sync(CorfuSMRObjectProxy.java:434)
        at org.corfudb.runtime.object.CorfuSMRObjectProxy.interceptAccessor(CorfuSMRObjectProxy.java:277)
        at org.corfudb.runtime.collections.SMRMap$ByteBuddy$uyKJrki9.isEmpty(Unknown Source)
        ... 8 more
```

This may or may not be a duplicate of https://github.com/CorfuDB/CorfuDB/issues/211, I'm not sure, sorry.

**Comment by slfritchie** [comment]
November review: not visible with today's master, will re-open if it re-surfaces.
