### ISSUE TITLE
Infinite loop of java.nio.file.NoSuchFileException exceptions

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#243]
Found on `master` branch as of commit d4d444329f7f15c6a9b5da1fd0465c5e1667131e, via QuickCheck.

The simplified & stand-alone reproducing script can be found at https://gist.github.com/slfritchie/a4cb6aef72169b06883bf0c6624a606d ... it's (truncated) output looks like:

```
sh -x ~/foo
+ SERVER_DIR=/tmp/some/path
+ TMP_JSON=/tmp/json-file42938
+ rm -rf /tmp/some/path
+ mkdir -p /tmp/some/path
+ cat
+ cp /tmp/json-file42938 /tmp/some/path/LAYOUTS_1
+ cp /tmp/json-file42938 /tmp/some/path/LAYOUT_CURRENT
+ rm /tmp/json-file42938
+ /bin/echo -n 1
+ server_pid=42946
+ sleep 5
+ ./bin/corfu_server -l /tmp/some/path 8000
[...]
Welcome to CORFU SERVER
[...]
 19:39:19.198 INFO  [LogUnit-GC] o.c.i.LogUnitServer - Garbage collection pass complete. Freed 0 entries
 19:39:19.369 INFO  [Config-Mgr-0] o.c.i.LayoutServer - Initial client layout for poller = Layout(layoutServers=[localhost:8000], sequencers=[localhost:8000], segments=[Layout.LayoutSegment(replicationMode=REPLEX, start=0, end=-1, stripes=[Layout.LayoutStripe(logServers=[localhost:8000])], replexes=[Layout.LayoutStripe(logServers=[localhost:8000])])], epoch=1)
 + ./bin/corfu_layout query localhost:8000
OK {
  "layoutServers": [
    "localhost:8000"
  ],
  "sequencers": [
    "localhost:8000"
  ],
  "segments": [
    {
      "replicationMode": "REPLEX",
      "start": 0,
      "end": -1,
      "stripes": [
        {
          "logServers": [
            "localhost:8000"
          ]
        }
      ],
      "replexes": [
        {
          "logServers": [
            "localhost:8000"
          ]
        }
      ]
    }
  ],
  "epoch": 1
}
+ client_pid=42971
+ sleep 5
+ ./bin/corfu_smrobject -c localhost:8000 -s 42 org.corfudb.runtime.collections.SMRMap put foo,some-val
19:39:24.705 INFO  [main] o.c.r.CorfuRuntime - Connecting to Corfu server instance, layout servers=[localhost:8000]
 19:39:25.465 INFO  [event-3] o.c.i.l.RollingLog - Opened new log file at /tmp/some/path/log0
 19:39:25.474 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[0]: Written to disk.
 19:39:25.481 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.482 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[0]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.487 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[1]: Written to disk.
 19:39:25.488 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.489 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[1]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.492 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[2]: Written to disk.
 19:39:25.494 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.494 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[2]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.497 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[3]: Written to disk.
 19:39:25.499 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.499 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[3]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.502 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[4]: Written to disk.
 19:39:25.504 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.505 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[4]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.508 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[5]: Written to disk.
 19:39:25.510 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.510 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[5]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.513 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[6]: Written to disk.
 19:39:25.514 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.515 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[6]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.518 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[7]: Written to disk.
 19:39:25.519 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.519 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[7]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.522 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[8]: Written to disk.
 19:39:25.524 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.525 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[8]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.527 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[9]: Written to disk.
 19:39:25.529 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.529 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[9]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.531 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[10]: Written to disk.
 19:39:25.533 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.533 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[10]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.535 INFO  [event-3] o.c.i.l.RollingLog - Disk_write[11]: Written to disk.
 19:39:25.537 ERROR [event-3] o.c.i.l.RollingLog - Error opening file 0
 java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
19:39:25.537 ERROR [event-3] o.c.i.l.RollingLog - Disk_write[11]: Exception
 java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at org.corfudb.infrastructure.log.RollingLog.lambda$getChannelForAddress$0(RollingLog.java:134)
Caused by: java.nio.file.NoSuchFileException: /tmp/some/path/log/a1d0c6e8-3f02-3327-9846-1063f4ac58a60
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[...]
```

**Comment by slfritchie** [comment]
Perhaps fixed by commit 5a5c0d56eb60258696c60037968a384cf4b7d57c in the branch `slf/map-qc-with-replex`?

**Comment by Maithem** [comment]
Please close if this has been fixed.

**Comment by slfritchie** [comment]
@Maithem I haven't seen it in a while, but that isn't proof by itself.  However, since `RollingLog.java` no longer exists on `master` branch, this particular exception won't be happening again.  `^_^`

The `getChannelForAddress()` method moved to `StreamLogFiles.java` and (by itself) has only minor changes.  But the environment around that method has changed quite a bit.  I'll close this.

**Comment by Maithem** [comment]
@slfritchie The way we use we mapped buffers is fragile, I'm planning to rip it out and replace it with an append file writer. Coming soon.
