### ISSUE TITLE
forceRemoveAfterSeal intermittent failure

### ISSUE THREAD

**Issue by annym** [CorfuDB/CorfuDB#2729]
## Overview

Please take a look at the following test with intermittent failure: forceRemoveAfterSeal

[ERROR]   ClusterReconfigIT.forceRemoveAfterSeal:1041 Expecting code to raise a throwable.
1437

Logs : [https://api.travis-ci.org/v3/job/719165008/log.txt](https://api.travis-ci.org/v3/job/719165008/log.txt)

**Comment by annym** [comment]
This failure is still occurring: [https://github.com/CorfuDB/CorfuDB/pull/2909/checks?check_run_id=2135826445](https://github.com/CorfuDB/CorfuDB/pull/2909/checks?check_run_id=2135826445)

`Error:  Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 428.368 s <<< FAILURE! - in org.corfudb.integration.ClusterReconfigIT
2460
Error:  org.corfudb.integration.ClusterReconfigIT.forceRemoveAfterSeal  Time elapsed: 19.881 s  <<< FAILURE!
2461
java.lang.AssertionError: 
2462

2463
Expecting code to raise a throwable.
2464
	at org.corfudb.integration.ClusterReconfigIT.forceRemoveAfterSeal(ClusterReconfigIT.java:1042)
2465
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2466
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2467
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2468
	at java.lang.reflect.Method.invoke(Method.java:498)
2469
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2470
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2471
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2472
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2473
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2474
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2475
	at org.corfudb.AbstractCorfuTest$1$1.lambda$evaluate$0(AbstractCorfuTest.java:95)
2476
	at java.lang.Thread.run(Thread.java:748)`
