### ISSUE TITLE
java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#275]
Found while trying to reproduce #273, see that ticket for background.

This exception would be thrown by the server very occasionally instead of the exception that #273 was trying to provoke.

    Exception in thread "event-1" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
    	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:121)
    	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440)
    	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
    	at ch.qos.logback.classic.Logger.warn(Logger.java:713)
    	at io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:876)
    	at java.lang.Thread.run(Thread.java:745)
    Exception in thread "threadDeathWatcher-2-1" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
    	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:121)
    	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440)
    	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
    	at ch.qos.logback.classic.Logger.warn(Logger.java:713)
    	at io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151)
    	at io.netty.util.ThreadDeathWatcher$Watcher.notifyWatchees(ThreadDeathWatcher.java:210)
    	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:143)
    	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by slfritchie** [comment]
Given the recent big code reorganization & its build artifact changes, I'll close this until it ever surfaces again.

**Comment by rdp** [comment]
Which version were you thinking was "past" this failure?
