### ISSUE TITLE
IT test verifyStateTransferWithChainHeadFailure fails intermittently on Travis

### ISSUE THREAD

**Issue by WenbinZhu** [CorfuDB/CorfuDB#2805]
## Overview

verifyStateTransferWithChainHeadFailure passes in local runs, but fails intermittently on Travis, might  be a timing race:

```
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 245.202 s <<< FAILURE! - in org.corfudb.integration.StateTransferIT
[ERROR] verifyStateTransferWithChainHeadFailure  Time elapsed: 74.677 s  <<< FAILURE!
java.lang.AssertionError: 
Expecting code not to raise a throwable but caught a
  <java.util.concurrent.CompletionException>
with message :
  "org.corfudb.runtime.exceptions.OverwriteException"
	at org.corfudb.integration.StateTransferIT.verifyStateTransferWithNodeFailure(StateTransferIT.java:188)
	at org.corfudb.integration.StateTransferIT.verifyStateTransferWithChainHeadFailure(StateTransferIT.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.corfudb.AbstractCorfuTest$1$1.lambda$evaluate$0(AbstractCorfuTest.java:106)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by annym** [comment]
Continues intermittently failing:

[Link to Failure](https://github.com/CorfuDB/CorfuDB/pull/3007/checks?check_run_id=3187447205)

Error:    StateTransferIT.verifyStateTransferWithChainHeadFailure:84->verifyStateTransferWithNodeFailure:190 
4791
Expecting code not to raise a throwable but caught
4792
  "java.util.concurrent.CompletionException: org.corfudb.runtime.exceptions.OverwriteException
4793
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
4794
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
4795
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1643)
4796
	at java.lang.Thread.run(Thread.java:748)
4797
Caused by: org.corfudb.runtime.exceptions.OverwriteException
4798
	at org.corfudb.runtime.view.AddressSpaceView.validateStateOfWrittenEntry(AddressSpaceView.java:175)
4799
	at org.corfudb.runtime.view.AddressSpaceView.lambda$null$4(AddressSpaceView.java:240)
4800
	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:132)
4801
	at org.corfudb.runtime.view.AddressSpaceView.lambda$write$5(AddressSpaceView.java:204)
4802
	at org.corfudb.common.metrics.micrometer.MicroMeterUtils.time(MicroMeterUtils.java:50)
4803
	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:251)
4804
	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:261)
4805
	at org.corfudb.integration.StateTransferIT.lambda$startWriter$10(StateTransferIT.java:285)
4806
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
4807
	... 1 more
