### ISSUE TITLE
add_layout example in getting started generates error

### ISSUE THREAD

**Issue by jsr** [CorfuDB/CorfuDB#284]
I'm following the instructions in your getting started guide and run into an error trying to add_layout. 

```
jrosoff in ~/src/CorfuDB/bin on master
$./corfu_layouts add_layout -c localhost:9000 -e localhost:9001
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat
Exception in thread "main" java.io.FileNotFoundException: /Users/jrosoff/src/CorfuDB/bin/../corfu_scripts/corfu_layouts.clj (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at clojure.java.io$eval3600$fn__3601.invoke(io.clj:229)
	at clojure.java.io$eval3491$fn__3492$G__3480__3499.invoke(io.clj:69)
	at clojure.java.io$eval3618$fn__3619.invoke(io.clj:258)
	at clojure.java.io$eval3491$fn__3492$G__3480__3499.invoke(io.clj:69)
	at clojure.java.io$fn__3558.invokeStatic(io.clj:165)
	at clojure.java.io$fn__3558.invoke(io.clj:165)
	at clojure.java.io$eval3491$fn__3505$G__3476__3512.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at clojure.core$slurp.invokeStatic(core.clj:6664)
	at clojure.core$slurp.doInvoke(core.clj:6657)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at org.corfudb.shell$_formify_file_base.invokeStatic(shell.clj:41)
	at org.corfudb.shell$_formify_file_base.invoke(shell.clj:41)
	at org.corfudb.shell$_formify_file.invokeStatic(shell.clj:47)
	at org.corfudb.shell$_formify_file.invoke(shell.clj:46)
	at org.corfudb.shell$_main.invokeStatic(shell.clj:75)
	at org.corfudb.shell$_main.doInvoke(shell.clj:50)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:186)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at org.corfudb.shell_main$_main.invokeStatic(shell_main.clj:6)
	at org.corfudb.shell_main$_main.doInvoke(shell_main.clj:4)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at org.corfudb.shell_main.main(Unknown Source)
^Cjrosoff in ~/src/CorfuDB/bin on master
```
The file it's looking for (`../corfu_scripts/corfu_layouts.clj`) does not exist 
```
$ ls ../corfu_scripts/
corfu_layout.clj corfu_query.clj  corfu_stream.clj
corfu_ping.clj   corfu_reset.clj
jrosoff in ~/src/CorfuDB/bin on master
```

**Comment by no2chem** [comment]
Hi Jared,

This error is because the clojure PR was merged in early. 

As a temporary workaround, you can revert to the old version of cmdlet.sh located here:
https://github.com/CorfuDB/CorfuDB/blob/de21269daf878126f6690fad612244935fed6617/scripts/cmdlet.sh

We'll have this patched up shortly, and the examples updated. Sorry about any confusion.

**Comment by no2chem** [comment]
Duplicate of #280

**Comment by jsr** [comment]
Thanks!
