### ISSUE TITLE
Stream Read NullPointerException

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#305]
Reading a stream address by address serially throws a null pointer exception.

Code:

    @Test
    public void SimpleStreamTest() throws Exception {

        CorfuRuntime rt = new CorfuRuntime(layoutServers).connect();
        rt.setCacheDisabled(true);

        UUID streamId = UUID.nameUUIDFromBytes("stream1".getBytes());

        StreamView s1 = rt.getStreamsView().get(streamId);

        // Verify that the stream is empty
        //assertThat(s1.check()).isEqualTo(-1);

        // Generate and write random data. Write 100 entries, each entry is 2mb
        int entrySize = 200;
        int numEntries = 100;
        byte[][] data = new byte[numEntries][entrySize];

        Random rand = new Random();

        for(int x = 0; x < numEntries; x++) {
            rand.nextBytes(data[x]);
            s1.write(data[x]);
        }

        // Read back the data and verify it is correct
        for(int x = 0; x < numEntries; x++) {
            LogData entry = s1.read(x);
            byte[] tmp = (byte[]) entry.getPayload(rt);
            
            assertThat(tmp).isEqualTo(data[x]);
        }
    }

stack trace

java.lang.NullPointerException
	at org.corfudb.protocols.logprotocol.LogEntry.deserialize(LogEntry.java:68)
	at org.corfudb.util.serializer.CorfuSerializer.deserialize(CorfuSerializer.java:41)
	at org.corfudb.protocols.wireprotocol.LogData.getPayload(LogData.java:39)
	at org.corfudb.runtime.view.StreamView.read(StreamView.java:292)
	at org.corfudb.StreamIT.SimpleStreamTest(StreamIT.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by Maithem** [comment]
Update.The null pointer exception is because bad serializer types are being read. I don't know if its improperly written, or if on the read the buffer pointer is not incremented properly, so when serializing a LogEntryType the wrong offset is read.
