### ISSUE TITLE
Reopening a tables which has been cleared and moved from RegistryTable could potentially hit TrimmedException

### ISSUE THREAD

**Issue by Lujie1996** [CorfuDB/CorfuDB#3251]
## Overview

**Bug report.** 
The following workflow could hit TrimmedException
1. Open table `A`.
2. Clear table `A` by appending a `clear` SMR operation. Remove it from RegistryTable.
3. Run checkpoint and trim for at least once. `A` is skipped checkpointing because it's no longer in RegistryTable.
4. Reopen table A. 

This can happen more frequently in Backup Restore. The DB is restored as part of upgrade rolling back. After restore, reopening a table which has been opened before has the same pattern as above.

This is the same issue we have seen before - as a common approach to deep-clean a table, we skip checkpointing the table for 3 times and it will be trimmed. We have to restart corfu server otherwise it hits TrimmedException.

**Comment by Lujie1996** [comment]
This test demonstrates the issue 
https://github.com/CorfuDB/CorfuDB/commit/15a9f6ee08558b45de44d65f1ecdd2b81570c40c

Stack trace

org.corfudb.runtime.exceptions.TrimmedException: getStreamAddressMap[{ab15@-1}] [-1, 6] stream has been trimmed at address 6 and this space is not covered by the loaded checkpoint with start address -1, while accessing the stream at version 6. Looking for a new checkpoint.`

	at org.corfudb.runtime.view.stream.AddressMapStreamView.moveToReadQueue(AddressMapStreamView.java:224)
	at org.corfudb.runtime.view.stream.AddressMapStreamView.discoverAddressSpace(AddressMapStreamView.java:159)
	at org.corfudb.runtime.view.stream.AbstractQueuedStreamView.fillReadQueue(AbstractQueuedStreamView.java:534)
	at org.corfudb.runtime.view.stream.AbstractQueuedStreamView.getNextEntry(AbstractQueuedStreamView.java:104)
	at org.corfudb.runtime.view.stream.AbstractQueuedStreamView.getNextEntry(AbstractQueuedStreamView.java:55)
	at org.corfudb.runtime.view.stream.AbstractContextStreamView.nextUpTo(AbstractContextStreamView.java:131)
	at org.corfudb.runtime.view.stream.StreamSpliterator.tryAdvance(StreamSpliterator.java:59)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
	at org.corfudb.runtime.object.VersionLockedObject.lambda$syncStreamUnsafe$5(VersionLockedObject.java:688)
	at org.corfudb.common.metrics.micrometer.MicroMeterUtils.time(MicroMeterUtils.java:115)
	at org.corfudb.runtime.object.VersionLockedObject.syncStreamUnsafe(VersionLockedObject.java:708)
	at org.corfudb.runtime.object.VersionLockedObject.syncObjectUnsafeInner(VersionLockedObject.java:372)
	at org.corfudb.runtime.object.VersionLockedObject.syncObjectUnsafe(VersionLockedObject.java:335)
	at org.corfudb.runtime.object.CorfuCompileProxy.lambda$accessInner$2(CorfuCompileProxy.java:180)
	at org.corfudb.runtime.object.VersionLockedObject.access(VersionLockedObject.java:258)
	at org.corfudb.runtime.object.CorfuCompileProxy.accessInner(CorfuCompileProxy.java:175)
	at org.corfudb.runtime.object.CorfuCompileProxy.lambda$access$0(CorfuCompileProxy.java:153)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.corfudb.common.metrics.micrometer.MicroMeterUtils.time(MicroMeterUtils.java:121)
	at org.corfudb.runtime.object.CorfuCompileProxy.access(CorfuCompileProxy.java:153)
	at org.corfudb.runtime.collections.CorfuTable$CORFUSMR.size(CorfuTable$CORFUSMR.java:150)
	at org.corfudb.runtime.collections.Table.count(Table.java:327)
	at org.corfudb.runtime.BackupRestoreIT.backupRestoreAllTablesTest2(BackupRestoreIT.java:863)`
