### ISSUE TITLE
Netty Possibly Leaking Direct Memoy

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#328]
Writing 30mb stream entries causes this error:

 18:42:03.942 INFO  [event-1] o.c.i.l.StreamLogFiles - Disk_write[37]: Written to disk.
 18:42:04.374 ERROR [event-1] o.c.i.NettyServerRouter - Error in handling inbound message, {}
 io.netty.handler.codec.DecoderException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 20971520 byte(s) of direct memory (used: 914358272, max: 932184064)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:252)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 20971520 byte(s) of direct memory (used: 914358272, max: 932184064)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)

**Comment by slfritchie** [comment]
Mid-June issues review: ping @Maithem

**Comment by Maithem** [comment]
Can't reproduce.
