### ISSUE TITLE
Writing Large Stream Entries Causing BufferOverflowException

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#337]
14:09:34.476 INFO  [event-1] o.c.i.l.StreamLogFiles - Disk_write[66]: Written to disk.
 14:09:34.537 ERROR [event-1] o.c.i.l.StreamLogFiles - Disk_write[67]: Exception
 java.nio.BufferOverflowException: null
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
14:09:34.538 ERROR [event-1] o.c.i.NettyServerRouter - Exception during read!
 java.lang.RuntimeException: java.nio.BufferOverflowException
	at org.corfudb.infrastructure.log.StreamLogFiles.append(StreamLogFiles.java:307)
Caused by: java.nio.BufferOverflowException: null
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)

**Comment by Maithem** [comment]
I was on an old branch, this patch fixed the problem #332 
its no longer present on master
