### ISSUE TITLE
Cannot start corfu_server: NoClassDefFoundError: org/apache/commons/io/FileUtils

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#342]
Starting with commit f087f5c9ff8af604552d68c6de65251ea7d68d22 as part of PR #334, it isn't possible to start the Corfu server when using the `-l` flag.  For example:

    rm -rf /tmp/some/path && ./bin/corfu_server -l /tmp/some/path -s -d WARN 8000

... will halt the server in the following exception:

     Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
    	at org.corfudb.infrastructure.log.StreamLogFiles.verifyLogs(StreamLogFiles.java:83)
    	at org.corfudb.infrastructure.log.StreamLogFiles.<init>(StreamLogFiles.java:75)
    	at org.corfudb.infrastructure.LogUnitServer.reboot(LogUnitServer.java:294)
    	at org.corfudb.infrastructure.LogUnitServer.<init>(LogUnitServer.java:246)
    	at org.corfudb.infrastructure.CorfuServer.main(CorfuServer.java:182)
    Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 5 more

Looks like an entry for a dependent package wasn't added to the Maven `pom.xml` file?

**Comment by Maithem** [comment]
I can't seem to find who removed this dependency. Anyways, I added it again.
