### ISSUE TITLE
Flaky test: DistributedCheckpointerTest.validateLivenessNonLeaderTest

### ISSUE THREAD

**Issue by xcchang** [CorfuDB/CorfuDB#3467]
## Overview

Recent running results: https://github.com/CorfuDB/CorfuDB/actions/runs/3753912170/jobs/6377842333

## Deliverables

- [ ] ...

**Comment by zfrenette** [comment]
```
Error:    ClusterReconfigIT.reconnectDisconnectedClient:963 
expected: [51]
but was : null
```

**Comment by chetangudisagar** [comment]
```
Error:  Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 23.967 s <<< FAILURE! - in org.corfudb.runtime.DistributedCheckpointerTest
Error:  org.corfudb.runtime.DistributedCheckpointerTest.validateLivenessNonLeaderTest  Time elapsed: 2.856 s  <<< FAILURE!
java.lang.AssertionError
	at org.corfudb.runtime.DistributedCheckpointerTest.validateLivenessNonLeaderTest(DistributedCheckpointerTest.java:493)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.corfudb.AbstractCorfuTest$1$1.lambda$evaluate$0(AbstractCorfuTest.java:95)
	at java.lang.Thread.run(Thread.java:750)
```
