### ISSUE TITLE
Catch disk errors (NODE_ID creation) during startup

### ISSUE THREAD

**Issue by xnull** [CorfuDB/CorfuDB#3577]
## Overview
Do not restart Corfu in case of disk failures during Corfu startup.
Corfu exits with an exception during [`ServerContext`](https://github.com/CorfuDB/CorfuDB/blob/4774025ed8c93cd8d285f3927b80dbe1d746461e/infrastructure/src/main/java/org/corfudb/infrastructure/CorfuServer.java#L342) creation if the `DataStore` can't read data files (see stack trace error). 

We can catch the exception and retry instead of finishing the process.

```
java.lang.RuntimeException: java.io.IOException: Input/output error
	at org.corfudb.infrastructure.datastore.DataStore.load(DataStore.java:195)
	at org.corfudb.infrastructure.datastore.DataStore.lambda$get$2(DataStore.java:217)
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2344)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.corfudb.infrastructure.datastore.DataStore.get(DataStore.java:215)
	at org.corfudb.infrastructure.ServerContext.generateNodeId(ServerContext.java:397)
	at org.corfudb.infrastructure.ServerContext.<init>(ServerContext.java:164)
	at org.corfudb.infrastructure.CorfuServer.startServer(CorfuServer.java:342)
	at org.corfudb.infrastructure.CorfuServer.main(CorfuServer.java:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:349)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Input/output error
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.file.Files.read(Files.java:3105)
	at java.nio.file.Files.readAllBytes(Files.java:3158)
	at org.corfudb.infrastructure.datastore.DataStore.load(DataStore.java:185)
	... 19 common frames omitted
```

**Comment by xnull** [comment]
done
