### ISSUE TITLE
ReplexSMRMapTest.loadsFollowedByGetsConcurrent fails intermittently.

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#359]
From https://travis-ci.org/CorfuDB/CorfuDB/builds/181772932#L1751, which is an experimental branch based on master at commit 8cb9464, TravisCI found a failure of the `loadsFollowedByGetsConcurrent` test:

    loadsFollowedByGetsConcurrent(org.corfudb.runtime.collections.ReplexSMRMapTest)  Time elapsed: 7.197 sec  <<< ERROR!
    java.lang.NullPointerException
    	at org.corfudb.util.CFUtils.getUninterruptibly(CFUtils.java:45)
    	at org.corfudb.util.CFUtils.getUninterruptibly(CFUtils.java:89)
    	at org.corfudb.runtime.view.ReplexReplicationView.write(ReplexReplicationView.java:152)
    	at org.corfudb.runtime.view.AddressSpaceView.lambda$write$1(AddressSpaceView.java:128)
    	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:69)
    	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:126)
    	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:120)
    	at org.corfudb.runtime.view.StreamView.acquireAndWrite(StreamView.java:119)
    	at org.corfudb.runtime.object.CorfuSMRObjectProxy.writeUpdateAndMapFuture(CorfuSMRObjectProxy.java:328)
    	at org.corfudb.runtime.object.CorfuSMRObjectProxy.interceptMutatorAccessor(CorfuSMRObjectProxy.java:246)
    	at org.corfudb.runtime.collections.SMRMap$ByteBuddy$2r46Wgbu.put(Unknown Source)
    	at org.corfudb.runtime.collections.SMRMapTest.lambda$loadsFollowedByGetsConcurrent$0(SMRMapTest.java:135)
    	at org.corfudb.AbstractCorfuTest.lambda$scheduleConcurrently$0(AbstractCorfuTest.java:145)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

The same test runs 10 times in a row on my Mac without failure.

**Comment by dahliamalkhi** [comment]
@slfritchie could you help isolate and detect the bug ? ... and then potentially suggest a way to fix?

**Comment by slfritchie** [comment]
Yes.  There are now several of these pesky things.  Hopefully they can all be fixed with the same hammer.

**Comment by slfritchie** [comment]
The trigger is likely fallout from bug #336 (though note that I'd commented that this was a possible consequence: https://github.com/CorfuDB/CorfuDB/pull/336#issuecomment-264011842).  However, the `NullPointerException` is (I think) due to misuse of `CFUtils.getUninterruptibly`, which warrants another bug.

**Comment by dahliamalkhi** [comment]
Replex not supported.

**Comment by slfritchie** [comment]
@dahliamalkhi Are we going to remove all Replex-related unit tests during this unsupported period?

**Comment by slfritchie** [comment]
NOTE: The timeout adjustments done by #336 need to be revisited.  Also, the misuse of CFUtils.getUninterruptibly() may not be limited to Replex code?

**Comment by dahliamalkhi** [comment]
Replex code and unit tests are integrated and will not be removed, but Replex is disabled by default. 

At the same time, no reason to an an open issue on this. And in any case, this form of report is not useful for anyone to follow up. We need a repeatable test, and perhaps some effort into where it breaks.
