### ISSUE TITLE
ReplexSMRMapTest.concurrentAbortTestMulti fails intermittently

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#361]
From https://travis-ci.org/CorfuDB/CorfuDB/builds/181791720#L1797, which is the branch for PR #360 based on master at commit 8cb9464b2efb0455a5d01063a055573aa35ca0f3, TravisCI found a failure of the `concurrentAbortTestMulti` test:

    concurrentAbortTestMulti(org.corfudb.runtime.collections.ReplexSMRMapTest)  Time elapsed: 8.852 sec  <<< ERROR!
    java.lang.NullPointerException
    	at org.corfudb.util.CFUtils.getUninterruptibly(CFUtils.java:45)
    	at org.corfudb.util.CFUtils.getUninterruptibly(CFUtils.java:89)
    	at org.corfudb.runtime.view.ReplexReplicationView.write(ReplexReplicationView.java:160)
    	at org.corfudb.runtime.view.AddressSpaceView.lambda$write$1(AddressSpaceView.java:128)
    	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:69)
    	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:126)
    	at org.corfudb.runtime.view.AddressSpaceView.write(AddressSpaceView.java:120)
    	at org.corfudb.runtime.view.StreamsView.acquireAndWrite(StreamsView.java:152)
    	at org.corfudb.runtime.view.StreamsView.write(StreamsView.java:89)
    	at org.corfudb.runtime.object.transactions.OptimisticTransactionalContext.commitTransaction(OptimisticTransactionalContext.java:224)
    	at org.corfudb.runtime.view.ObjectsView.TXEnd(ObjectsView.java:263)
    	at org.corfudb.runtime.collections.SMRMapTest.lambda$concurrentAbortTestMulti$15(SMRMapTest.java:472)
    	at org.corfudb.AbstractCorfuTest.lambda$scheduleConcurrently$0(AbstractCorfuTest.java:145)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

The same test runs 10 times in a row on my Mac without failure.

**Comment by dahliamalkhi** [comment]
Replex currently not supported, and version 1.0 will ship with Replex disabled.
