### ISSUE TITLE
CorfuSMRObjectProxyTest & StreamViewTest intermittent failures

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#362]
From https://travis-ci.org/CorfuDB/CorfuDB/builds/181791001#L1696 and https://travis-ci.org/CorfuDB/CorfuDB/builds/181791001#L1820, which is an experimental branch based on master at commit 8cb9464, TravisCI found a failure of the `CorfuSMRObjectProxyTest.deadLockTest ` and `StreamViewTest.canReadWriteFromStreamConcurrent` tests.

deadLockTest(org.corfudb.runtime.object.CorfuSMRObjectProxyTest)  Time elapsed: 5.997 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[fals]e> but was:<[tru]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.corfudb.runtime.object.CorfuSMRObjectProxyTest.deadLockTest(CorfuSMRObjectProxyTest.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	[...]
and

Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.246 sec <<< FAILURE! - in org.corfudb.runtime.view.StreamViewTest
canReadWriteFromStreamConcurrent(org.corfudb.runtime.view.StreamViewTest)  Time elapsed: 5.997 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<null> but was:<org.corfudb.protocols.wireprotocol.LogData@c1312e6>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.corfudb.runtime.view.StreamViewTest.canReadWriteFromStreamConcurrent(StreamViewTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
        [...]

**Comment by dahliamalkhi** [comment]
This PR has since passed all tests and has been merged
