### ISSUE TITLE
Race Condition and Deadlock Scenario Between Seal Protocol and Persistence of LogUnit Metadata

### ISSUE THREAD

**Issue by zfrenette** [CorfuDB/CorfuDB#3862]
Today, there is a deadlock inducing scenario between Corfu's seal protocol and the periodic persistence of LogUnit metadata. This can occur during server initialization or during layout reconfiguration. The race condition plays out as follows:

1) The LogUnit-BatchProcessor-0 thread begins processing a DUMP_LOG_METADATA operation that was added to its queue by the LogMetadataRecorder thread. The thread calls StreamLogFiles::persistLogMetadata but has not yet called ServerContext::setLogUnitMetadata [synchronized].

2) Meanwhile, Corfu's seal protocol takes place. The baseServer-0 thread processes a SEAL message, and calls ServerContext::setServerEpoch [synchronized].

3) As part of this method call, each server component is sealed with the provided epoch. When this occurs for the LogUnit server via LogUnitServer::sealServerWithEpoch, a task is submitted to the BatchProcessor's queue and the baseServer-0 thread waits for this future to complete.

4) The LogUnit-BatchProcessor-0 thread now calls ServerContext::setLogUnitMetadata, but blocks on the ServerContext object monitor since it has already been acquired by the baseServer-0 thread.

5) The baseServer-0 thread cannot proceed since it is waiting for the LogUnit-BatchProcessor-0 thread to complete the future. Likewise, the LogUnit-BatchProcessor-0 thread cannot proceed since it is waiting for the baseServer-0 to release the ServerContext monitor lock.

Stack traces of relevant threads is included below:

"baseServer-0" #45 daemon prio=5 os_prio=0 tid=0x00007128dc24c800 nid=0x12696 waiting on condition [0x000071291b2ad000]
    java.lang.Thread.State: WAITING (parking)
       at sun.misc.Unsafe.park(Native Method)
       - parking to wait for  <0x00007129cf801568> (a java.util.concurrent.CompletableFuture$Signaller)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
       at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
       at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
       at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
       at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
       at org.corfudb.infrastructure.LogUnitServer.sealServerWithEpoch(LogUnitServer.java:522)
       at org.corfudb.infrastructure.ServerContext.lambda$setServerEpoch$5(ServerContext.java:576)
       at org.corfudb.infrastructure.ServerContext$$Lambda$482/426661297.accept(Unknown Source)
       at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
       at org.corfudb.infrastructure.ServerContext.setServerEpoch(ServerContext.java:576)
       - locked <0x00007129cffecf60> (a org.corfudb.infrastructure.ServerContext)
       at org.corfudb.infrastructure.BaseServer.handleSeal(BaseServer.java:93)
       - locked <0x00007129cfc1b460> (a org.corfudb.infrastructure.BaseServer)
       at org.corfudb.infrastructure.BaseServer$$Lambda$87/1781396220.handle(Unknown Source)
       at org.corfudb.infrastructure.RequestHandlerMethods.lambda$null$2(RequestHandlerMethods.java:169)
       at org.corfudb.infrastructure.RequestHandlerMethods$$Lambda$464/328613569.run(Unknown Source)
       at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
       at org.corfudb.common.metrics.micrometer.MicroMeterUtils.time(MicroMeterUtils.java:115)
       at org.corfudb.infrastructure.RequestHandlerMethods.lambda$generateConditionalHandler$3(RequestHandlerMethods.java:169)
       at org.corfudb.infrastructure.RequestHandlerMethods$$Lambda$86/1547707959.handle(Unknown Source)
       at org.corfudb.infrastructure.RequestHandlerMethods.handle(RequestHandlerMethods.java:90)
       at org.corfudb.infrastructure.BaseServer.lambda$processRequest$0(BaseServer.java:51)
       at org.corfudb.infrastructure.BaseServer$$Lambda$463/877558727.run(Unknown Source)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:750)
       
 "LogUnit-BatchProcessor-0" #32 prio=5 os_prio=0 tid=0x0000712940560800 nid=0x125ec waiting for monitor entry [0x00007129c9a2d000]
    java.lang.Thread.State: BLOCKED (on object monitor)
       at org.corfudb.infrastructure.ServerContext.setLogUnitMetadata(ServerContext.java:666)
       - waiting to lock <0x00007129cffecf60> (a org.corfudb.infrastructure.ServerContext)
       at org.corfudb.infrastructure.log.StreamLogFiles.persistLogMetadata(StreamLogFiles.java:292)
       at org.corfudb.infrastructure.BatchProcessor.process(BatchProcessor.java:203)
       at org.corfudb.infrastructure.BatchProcessor$$Lambda$201/638059786.run(Unknown Source)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:750)
       
When this occurs during server initialization, one can also observe the following, preventing the ManagementServer from starting up:

 "initializationTaskThread" #35 prio=5 os_prio=0 tid=0x000071294059c000 nid=0x125f9 waiting for monitor entry [0x00007129c9596000]
    java.lang.Thread.State: BLOCKED (on object monitor)
       at org.corfudb.infrastructure.ServerContext.saveManagementLayout(ServerContext.java:617)
       - waiting to lock <0x00007129cffecf60> (a org.corfudb.infrastructure.ServerContext)
       at org.corfudb.infrastructure.ManagementAgent.tryImmediateRecovery(ManagementAgent.java:187)
       at org.corfudb.infrastructure.ManagementAgent.initializationTask(ManagementAgent.java:230)
       at org.corfudb.infrastructure.ManagementAgent$$Lambda$217/347829786.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:750)

**Comment by zfrenette** [comment]
PR with fix has been merged.
