### ISSUE TITLE
CorfuRuntime.connect() continuously consumes file descriptors

### ISSUE THREAD

**Issue by goyalkapil** [CorfuDB/CorfuDB#442]
I am using the runtime JAR from nsx maven repo from 01/25/2017.

If the Corfu server isn't available, CorfuRuntime.connect() continues to try to connect in a while loop. I suspect it consumes FDs that it doesn't release before the next attempt. After letting it run for some time, it throws this exception:

2017-02-14 16:03:49.024 PST  WARN ForkJoinPool.commonPool-worker-1 CorfuRuntime - Couldn't connect to any layout servers, retrying in 5s.
2017-02-14 16:03:56.231 PST  WARN ForkJoinPool.commonPool-worker-1 CorfuRuntime - Tried to get layout from localhost:9000 but failed with exception:
java.lang.IllegalStateException: failed to create a child event loop
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at org.corfudb.runtime.clients.NettyClientRouter.start(NettyClientRouter.java:214) ~[runtime-0.1-SNAPSHOT.jar:?]
        at org.corfudb.runtime.clients.NettyClientRouter.start(NettyClientRouter.java:205) ~[runtime-0.1-SNAPSHOT.jar:?]
        at org.corfudb.runtime.clients.NettyClientRouter.<init>(NettyClientRouter.java:164) ~[runtime-0.1-SNAPSHOT.jar:?]
        at org.corfudb.runtime.CorfuRuntime.lambda$new$1(CorfuRuntime.java:121) ~[runtime-0.1-SNAPSHOT.jar:?]
        at org.corfudb.runtime.CorfuRuntime.getRouter(CorfuRuntime.java:271) ~[runtime-0.1-SNAPSHOT.jar:?]
        at org.corfudb.runtime.CorfuRuntime.lambda$fetchLayout$3(CorfuRuntime.java:306) ~[runtime-0.1-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_60]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_60]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_60]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_60]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_60]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_60]
Caused by: io.netty.channel.ChannelException: failed to open a new selector
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:157) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        ... 18 more
Caused by: java.io.IOException: Too many open files
        at sun.nio.ch.IOUtil.makePipe(Native Method) ~[?:1.8.0_60]
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65) ~[?:1.8.0_60]
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36) ~[?:1.8.0_60]
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:155) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        ... 18 more

**Comment by dahliamalkhi** [comment]
You are right @goyalkapil . I am pushing a fix now. 

The cleaner, 'router' branch that @no2chem is working on, will obviate the need for this anyhow, but we might as well fix it for now.
