### ISSUE TITLE
Fix exception in stream view metrics management in rare race

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#664]
While running many hundreds of multithreaded tests during review of #648, I encountered this rare error twice.

    Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 24.175 sec <<< FAILURE! - in org.corfudb.runtime.checkpoint.CheckpointTest
    YooTest(org.corfudb.runtime.checkpoint.CheckpointTest)  Time elapsed: 11.98 sec  <<< ERROR!
    java.lang.IllegalArgumentException: A metric named corfu.runtime.as-view.0x620d9656.cache.cache-size already exists
            at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
            at org.corfudb.runtime.view.AddressSpaceView.<init>(AddressSpaceView.java:61)
            at org.corfudb.runtime.CorfuRuntime.getAddressSpaceView(CorfuRuntime.java:63)
            at org.corfudb.runtime.view.stream.BackpointerStreamView.fillReadQueue(BackpointerStreamView.java:251)
            at org.corfudb.runtime.view.stream.AbstractQueuedStreamView.getNextEntry(AbstractQueuedStreamView.java:72)
            at org.corfudb.runtime.view.stream.AbstractQueuedStreamView.getNextEntry(AbstractQueuedStreamView.java:31)
            at org.corfudb.runtime.view.stream.AbstractContextStreamView.nextUpTo(AbstractContextStreamView.java:132)
            at org.corfudb.runtime.view.stream.StreamSpliterator.tryAdvance(StreamSpliterator.java:57)
            at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
            at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
            at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
            at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
            at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
            at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
            at org.corfudb.runtime.object.VersionLockedObject.syncStreamUnsafe(VersionLockedObject.java:523)
            at org.corfudb.runtime.object.VersionLockedObject.syncObjectUnsafe(VersionLockedObject.java:284)
            at org.corfudb.runtime.object.CorfuCompileProxy.lambda$accessInner$1(CorfuCompileProxy.java:153)
            at org.corfudb.runtime.object.VersionLockedObject.access(VersionLockedObject.java:184)
            at org.corfudb.runtime.object.CorfuCompileProxy.accessInner(CorfuCompileProxy.java:151)
            at org.corfudb.runtime.object.CorfuCompileProxy.access(CorfuCompileProxy.java:127)
            at org.corfudb.runtime.collections.SMRMap$CORFUSMR.size(SMRMap$CORFUSMR.java:232)
            at org.corfudb.runtime.checkpoint.CheckpointTest.lambda$periodicCkpointTrimTest$9(CheckpointTest.java:239)
            at org.corfudb.AbstractCorfuTest.lambda$scheduleConcurrently$0(AbstractCorfuTest.java:297)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:748)

**Comment by Maithem** [comment]
We haven't seen this in a very long time. Closing for now.
