### ISSUE TITLE
ckCommitAtomicity fails intermittently

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#802]
See https://travis-ci.org/CorfuDB/CorfuDB/builds/250437301#L3839 for context of this `org.corfudb.runtime.concurrent.StreamSeekAtomicityTest` unit test suite failure.

Particularly noteworthy:

    Caused by: java.lang.NullPointerException
    	at org.corfudb.runtime.object.transactions.OptimisticTransactionalContext.lambda$access$0(OptimisticTransactionalContext.java:101)
    	at org.corfudb.runtime.object.VersionLockedObject.access(VersionLockedObject.java:180)
    	at org.corfudb.runtime.object.transactions.OptimisticTransactionalContext.access(OptimisticTransactionalContext.java:95)
    	at org.corfudb.runtime.object.CorfuCompileProxy.accessInner(CorfuCompileProxy.java:162)
    	... 8 more

**Comment by Maithem** [comment]
The problem seems to have been fixed.
