### ISSUE TITLE
periodicCkpointTrimTest fails intermittently in BatchWriter

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#816]
See https://travis-ci.org/CorfuDB/CorfuDB/builds/251210015#L3102 and https://travis-ci.org/CorfuDB/CorfuDB/builds/251901263#L3100 for the full context of these failures.

Note: this failure has a different cause than #779's failures.

Summary stack trace:

**Comment by slfritchie** [comment]
periodicCkpointTrimTest(org.corfudb.runtime.checkpoint.CheckpointTest)  Time elapsed: 5.127 sec  <<< ERROR!
    java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.corfudb.runtime.exceptions.TrimmedException
    	at org.corfudb.infrastructure.BatchWriter.prefixTrim(BatchWriter.java:97)
    	at org.corfudb.infrastructure.LogUnitServer.prefixTrim(LogUnitServer.java:247)
    	at org.corfudb.infrastructure.CorfuMsgHandler.lambda$null$1(CorfuMsgHandler.java:148)
    	at org.corfudb.infrastructure.CorfuMsgHandler.handle(CorfuMsgHandler.java:78)
    	at org.corfudb.infrastructure.AbstractServer.handleMessage(AbstractServer.java:51)
    	at org.corfudb.infrastructure.TestServerRouter.sendServerMessage(TestServerRouter.java:127)
    	at org.corfudb.runtime.clients.TestClientRouter.routeMessage(TestClientRouter.java:135)
    	at org.corfudb.runtime.clients.TestClientRouter.sendMessageAndGetCompletable(TestClientRouter.java:201)
    	at org.corfudb.runtime.clients.IClientRouter.sendMessageAndGetCompletable(IClientRouter.java:61)
    	at org.corfudb.runtime.clients.LogUnitClient.prefixTrim(LogUnitClient.java:368)
    	at org.corfudb.runtime.view.AddressSpaceView.lambda$null$15(AddressSpaceView.java:223)
    	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
    	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
    	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    	at org.corfudb.runtime.view.AddressSpaceView.lambda$prefixTrim$16(AddressSpaceView.java:224)
    	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:76)
    	at org.corfudb.runtime.view.AddressSpaceView.prefixTrim(AddressSpaceView.java:216)
    	at org.corfudb.runtime.checkpoint.CheckpointTest.mapCkpointAndTrim(CheckpointTest.java:103)
    	at org.corfudb.runtime.checkpoint.CheckpointTest.lambda$periodicCkpointTrimTest$8(CheckpointTest.java:317)
    	at org.corfudb.AbstractCorfuTest.lambda$scheduleConcurrently$0(AbstractCorfuTest.java:297)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.util.concurrent.ExecutionException: org.corfudb.runtime.exceptions.TrimmedException
    	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
    	at org.corfudb.infrastructure.BatchWriter.prefixTrim(BatchWriter.java:95)
    	... 35 more
    Caused by: org.corfudb.runtime.exceptions.TrimmedException
    	at org.corfudb.infrastructure.log.InMemoryStreamLog.prefixTrim(InMemoryStreamLog.java:63)
    	at org.corfudb.infrastructure.BatchWriter.batchWriteProcessor(BatchWriter.java:155)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	... 4 more

**Comment by Maithem** [comment]
@slfritchie This means you tried to prefix trim and address twice, or you tried to prefix trim -1?

**Comment by slfritchie** [comment]
@Maithem If the recent patch to skip over empty maps means skipping writing anything twice in a row, then yes, I think that `CheckpointWriter::mapCkpointAndTrim` could trim the same address twice because the maps were empty in two iterations.

**Comment by Maithem** [comment]
That makes sense. Thanks for checking it out.
We had a discussion about whether we should throw a trimmed exception if a trimmed address is trimmed again or not, but there was not consensus. Initially, when I implemented this, I needed this behavior to support parallel checkpointing.

**Comment by Maithem** [comment]
This problem seems to have disappeared, please re-open if you see it again.
