### ISSUE TITLE
Server Concurency Issue

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#837]
The server starts failing requests under reasonable concurrency. As a result, the channel and the client fails with a NetworkException. This can be reproduced by running the main function in #836.

Server log:

2017-07-15 01:11:28,283 ERROR [event-5] o.c.i.NettyServerRouter - Error in handling inbound message, {}
 io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
Caused by: java.lang.NullPointerException: null
	at org.corfudb.protocols.wireprotocol.ICorfuPayload.enumMapFromBuffer(ICorfuPayload.java:260)
2017-07-15 01:11:28,283 ERROR [event-5] o.c.i.NettyServerRouter - Error in handling inbound message, {}
 io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Attempt to deserialize a message which is not a CorfuMsg, Marker = 0 but expected 0xC0FC0FC0
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
Caused by: java.lang.RuntimeException: Attempt to deserialize a message which is not a CorfuMsg, Marker = 0 but expected 0xC0FC0FC0
	at org.corfudb.protocols.wireprotocol.CorfuMsg.deserialize(CorfuMsg.java:80)

@no2chem any ideas?

**Comment by Maithem** [comment]
This problem seems to have disappeared. Closing.
