### ISSUE TITLE
Transaction Aborted

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#839]
Transaction aborted with the cause set to null.

Can be reproduced with https://github.com/CorfuDB/CorfuDB/pull/838

Stack trace:

02:20:57.823 WARN  [ForkJoinPool-1-worker-0] o.c.r.v.ObjectsView - TXCommit[TX[3bc4]] Exception {}
 org.corfudb.runtime.exceptions.TransactionAbortedException: 968 ms
	at org.corfudb.runtime.view.StreamsView.append(StreamsView.java:118)
	at org.corfudb.runtime.object.transactions.OptimisticTransactionalContext.getConflictSetAndCommit(OptimisticTransactionalContext.java:271)
	at org.corfudb.runtime.object.transactions.OptimisticTransactionalContext.commitTransaction(OptimisticTransactionalContext.java:232)
null

**Comment by Maithem** [comment]
This seems to be caused by a NullPointerException that happens during deserialization, as a consequence the channel is closed and a NetworkException is thrown. 


org.corfudb.runtime.exceptions.NetworkException: Disconnected [endpoint=localhost:9000]
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.corfudb.protocols.wireprotocol.ICorfuPayload.enumMapFromBuffer(ICorfuPayload.java:260)
	at org.corfudb.protocols.wireprotocol.LogData.<init>(LogData.java:111)
	at org.corfudb.protocols.wireprotocol.ICorfuPayload.fromBuffer(ICorfuPayload.java:98)
	at org.corfudb.protocols.wireprotocol.ICorfuPayload.mapFromBuffer(ICorfuPayload.java:170)
	at org.corfudb.protocols.wireprotocol.ReadResponse.<init>(ReadResponse.java:23)
	at org.corfudb.protocols.wireprotocol.ICorfuPayload.fromBuffer(ICorfuPayload.java:98)
	at org.corfudb.protocols.wireprotocol.CorfuPayloadMsg.fromBuffer(CorfuPayloadMsg.java:58)
	at org.corfudb.protocols.wireprotocol.CorfuMsg.deserialize(CorfuMsg.java:93)
	at org.corfudb.protocols.wireprotocol.NettyCorfuMessageDecoder.decode(NettyCorfuMessageDecoder.java:21)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 7 more

**Comment by Maithem** [comment]
Can't reproduce.
