### ISSUE TITLE
testSequencerFailover test fails intermittently

### ISSUE THREAD

**Issue by slfritchie** [CorfuDB/CorfuDB#850]
Also reported by #595.  Recently this has appeared in Travis-CI builds on branch `xxHash` in build https://travis-ci.org/CorfuDB/CorfuDB/builds/254242363#L3349 and on branch `sequencerTxCleanup` in build https://travis-ci.org/CorfuDB/CorfuDB/builds/251095057#L3362.

    testSequencerFailover                                       [FAIL - ComparisonFailure:L445]
    sequencerFailoverBackpointerCheck                           [PASS]
    removeSingleNodeFailure                                     [PASS]
    Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 52.471 sec <<< FAILURE! - in org.corfudb.runtime.view.ManagementViewTest
    testSequencerFailover(org.corfudb.runtime.view.ManagementViewTest)  Time elapsed: 5.078 sec  <<< FAILURE!
    org.junit.ComparisonFailure: expected:<...nresponsiveServers=[[test:1], epoch=2])> but was:<...nresponsiveServers=[[], epoch=3])>
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at org.corfudb.runtime.view.ManagementViewTest.testSequencerFailover(ManagementViewTest.java:445)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [...]

**Comment by zalokhan** [comment]
Fixed this in #624
