### ISSUE TITLE
Stream Sync IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#853]
There seems to be a concurrency issue when running operations concurrently. An IndexOutOfBoundsException is thrown. The problem can be reproduced using the load generator. 

Stacktrace
java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Collections.java:4454)
at org.corfudb.runtime.object.transactions.WriteSetSMRStream.current(WriteSetSMRStream.java:177)
at org.corfudb.runtime.object.transactions.WriteSetSMRStream.previous(WriteSetSMRStream.java:215)
at org.corfudb.runtime.object.VersionLockedObject.rollbackStreamUnsafe(VersionLockedObject.java:563)
at org.corfudb.runtime.object.VersionLockedObject.optimisticRollbackUnsafe(VersionLockedObject.java:620)
at org.corfudb.runtime.object.VersionLockedObject.syncObjectUnsafe(VersionLockedObject.java:312)
at org.corfudb.runtime.object.CorfuCompileProxy.lambda$getUpcallResultInner$5(CorfuCompileProxy.java:284)
at org.corfudb.runtime.object.VersionLockedObject.update(VersionLockedObject.java:243)
at org.corfudb.runtime.object.CorfuCompileProxy.getUpcallResultInner(CorfuCompileProxy.java:283)
at org.corfudb.runtime.object.CorfuCompileProxy.getUpcallResult(CorfuCompileProxy.java:236)
at org.corfudb.runtime.collections.SMRMap$CORFUSMR.put(SMRMap$CORFUSMR.java:173)
at org.corfudb.generator.operations.WriteOperation.execute(WriteOperation.java:22)
at org.corfudb.generator.main.lambda$main$1(main.java:44)
at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by Maithem** [comment]
Fixed by https://github.com/CorfuDB/CorfuDB/pull/854
