### ISSUE TITLE
NPE on Operation

### ISSUE THREAD

**Issue by Maithem** [CorfuDB/CorfuDB#975]
When an operation is invoked on the runtime before connecting a NPE is thrown.

**Comment by no2chem** [comment]
@Maithem Does this issue still exist?

**Comment by Maithem** [comment]
Yes, stacktrace below

`Exception in thread "Thread-2" java.lang.NullPointerException
	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:89)
	at org.corfudb.runtime.view.AbstractView.layoutHelper(AbstractView.java:59)
	at org.corfudb.runtime.view.SequencerView.nextToken(SequencerView.java:34)
	at org.corfudb.integration.StreamIT.lambda$simpleStreamTest$0(StreamIT.java:35)`

**Comment by Maithem** [comment]
outdated.
