### ISSUE TITLE
Out of memory error. Corfu process heap memory was around 200mb

### ISSUE THREAD

**Issue by vaibhavkulkar** [CorfuDB/CorfuDB#98]
01:09:27.719 ERROR [event-1] o.c.i.NettyServerRouter - Error in handling inbound message, {}
io.netty.handler.codec.DecoderException: java.lang.OutOfMemoryError: Direct buffer memory
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [corfu-0.1-SNAPSHOT-shaded.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658) ~[na:1.8.0_51]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[na:1.8.0_51]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[na:1.8.0_51]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.allocateDirect(UnpooledUnsafeDirectByteBuf.java:106) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.capacity(UnpooledUnsafeDirectByteBuf.java:155) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:268) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:249) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:866) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:858) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:848) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:92) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242) ~[corfu-0.1-SNAPSHOT-shaded.jar:na]
	... 10 common frames omitted

**Comment by no2chem** [comment]
Hi there, could you tell us a little more about this issue? For example, how many clients did you have and how many log entries there were when this occurred? Thanks!

**Comment by vaibhavkulkar** [comment]
Hey,

I used following snippet to connect to corfu and create a map, only 1 client.

CorfuRuntime rt = new CorfuRuntime("localhost:9000").connect();
        Map<Object, Object> map = rt.getObjectsView().open(CorfuRuntime.getStreamID("A"), SMRMap.class);
        Integer previous = (Integer) map.get("a");
        if (previous == null) {
            System.out.println("This is the first time we were run!");
            map.put("a", 1);
        } else {
            map.put("a", ++previous);
            System.out.println("This is the " + previous + " time we were run!");
        }

Then I started putting objects in Map (treating it like java hashmap). Before getting above exception I had put around 140000 objects in map. Corfu process heap memory was around 210mb and client memory was around 500mb. I am trying to profile jvisual vm, If I get some thing more interesting will share that too.

**Comment by no2chem** [comment]
Ok - can you tell me a little bit more about how you invoked corfu_server (was this in memory or to a log file?)  Thanks!

**Comment by vaibhavkulkar** [comment]
Started corfu server with following command: corfu_server -ms 9000

Also I took corfu code a week back and build server locally on my machine.

**Comment by no2chem** [comment]
Cool, thanks for that information. So that's in memory mode, and it seems like the implementation is just running out of memory here at around 140k objects (4k?). In the current in-memory mode implementation, the server just takes the buffer from netty and puts it in a Caffeine cache. The Caffeine cache is supposed to limit the size of the cache (default = 1GB), so you might try lowering that limit. 140k 4KB object seems awfully close to 512MB, which I think is the default Java heap size.

Could you try running the log unit not in-memory mode? corfu_server -l /tmp/corfu -s 9000 ?

**Comment by Maithem** [comment]
@no2chem @vaibhavkulkar  There is a bug in the start script. When starting the server the amount of heap available to the server is the default value of Xmx (which was 256mb for me), not 1000mb.

If you look here : https://github.com/CorfuDB/CorfuDB/blob/master/scripts/corfu_server.sh#L43 The JVMFLAGS is actually empty, so the jvm doesn't start with -Xmx=1000m. Since you encountered the issue with heap usage around 210mb, then your jvm might also be defaulting to a smaller heap.

As a temporary solution you can export JVMFLAGS =-Xmx1000m before starting running the server.

**Comment by vaibhavkulkar** [comment]
1. Same error with export JVMFLAGS =-Xmx1000m. 
2. Same error with corfu_server -l /tmp/corfu -s 9000

With 2nd option heap memory used was much less on both client(180mb) and corfu server side(140mb) it's probably because of not in-memory mode.
Exception in client: 
02:04:11.240 WARN  [ForkJoinPool.commonPool-worker-4] o.c.r.CorfuRuntime - Couldn't connect to any layout servers, retrying in 5s.
02:04:11.240 WARN  [ForkJoinPool.commonPool-worker-16] o.c.r.CorfuRuntime - Tried to get layout from localhost:9000 but failed with exception:
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Timeout after 5000 ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_51]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887) ~[na:1.8.0_51]
	at org.corfudb.runtime.CorfuRuntime.lambda$fetchLayout$2(CorfuRuntime.java:215) ~[corfu-0.1-SNAPSHOT.jar:na]
	at org.corfudb.runtime.CorfuRuntime$$Lambda$20/294834677.get(Unknown Source) [corfu-0.1-SNAPSHOT.jar:na]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) [na:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) [na:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [na:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [na:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [na:1.8.0_51]
Caused by: java.util.concurrent.TimeoutException: Timeout after 5000 ms
	at org.corfudb.util.CFUtils.lambda$failAfter$78(CFUtils.java:87) ~[corfu-0.1-SNAPSHOT.jar:na]
	at org.corfudb.util.CFUtils$$Lambda$32/310726779.call(Unknown Source) ~[na:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_51]

**Comment by no2chem** [comment]
@Maithem thanks for that, putting through a pull request that I referenced here.

@vaibhavkulkar that doesn't seem to be the same exception at all - it seems your client can't contact the layout server for some reason. Does that client run successfully for awhile and then do that?

**Comment by vaibhavkulkar** [comment]
Yes. Client runs for around 20 minutes before giving the error. Client is constantly pushing data in corfu.

**Comment by no2chem** [comment]
Ok thanks. I'm looking into the buffer allocations to see if there's anything wrong there.

**Comment by no2chem** [comment]
Hi all, #140  closes this bug.
