### ISSUE TITLE
Server JVM OutOfMemory on startup with large log files

### ISSUE THREAD

**Issue by zalokhan** [CorfuDB/CorfuDB#986]
Sever fails to startup when a log file has size more than 2GB (JVM heap limit)

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at org.corfudb.infrastructure.log.StreamLogFiles.readAddressSpace(StreamLogFiles.java:633)
	at org.corfudb.infrastructure.log.StreamLogFiles.lambda$getSegmentHandleForAddress$2(StreamLogFiles.java:770)
	at org.corfudb.infrastructure.log.StreamLogFiles$$Lambda$43/1899223686.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.corfudb.infrastructure.log.StreamLogFiles.getSegmentHandleForAddress(StreamLogFiles.java:751)
	at org.corfudb.infrastructure.log.StreamLogFiles.initializeMaxGlobalAddress(StreamLogFiles.java:245)
	at org.corfudb.infrastructure.log.StreamLogFiles.<init>(StreamLogFiles.java:113)
	at org.corfudb.infrastructure.LogUnitServer.<init>(LogUnitServer.java:124)
	at org.corfudb.infrastructure.CorfuServer.addLogUnit(CorfuServer.java:487)
	at org.corfudb.infrastructure.CorfuServer.main(CorfuServer.java:278)
```

**Comment by no2chem** [comment]
@zalokhan Can you still reproduce this issue?

**Comment by zalokhan** [comment]
Yes this is still reproducible.

**Comment by Maithem** [comment]
#1048 has more information about the same problem. Closing this.
